# GENERATED by tools/regen.py -- do not edit.
import pytest
import accudist as ad


@pytest.mark.parametrize("name", ['ppois'])
def test_manifest_function_is_public(name):
    assert callable(getattr(ad, name))
    assert name in ad.__all__
