# GENERATED by tools/regen.py -- do not edit.
from __future__ import annotations

from . import _dispatch, _errstate, _rng, _ufuncs

def dnorm(x, mean=0.0, sd=1.0, log=False, out=None):
    """dnorm backed by R 4.5.2 nmath."""
    with _errstate.capture("dnorm") as _capture:
        result = _ufuncs.dnorm(x, mean, sd, int(log), out=out)
    _capture.check()
    return result

def pnorm(q, mean=0.0, sd=1.0, lower_tail=True, log=False, out=None):
    """pnorm backed by R 4.5.2 nmath."""
    with _errstate.capture("pnorm") as _capture:
        result = _ufuncs.pnorm(q, mean, sd, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qnorm(p, mean=0.0, sd=1.0, lower_tail=True, log=False, out=None):
    """qnorm backed by R 4.5.2 nmath."""
    with _errstate.capture("qnorm") as _capture:
        result = _ufuncs.qnorm(p, mean, sd, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rnorm(n, mean=0.0, sd=1.0):
    """rnorm backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rnorm") as _capture:
        result = _rng.draw(_ufuncs.rnorm, n, mean, sd)
    _capture.check()
    return result

def dunif(x, min=0.0, max=1.0, log=False, out=None):
    """dunif backed by R 4.5.2 nmath."""
    with _errstate.capture("dunif") as _capture:
        result = _ufuncs.dunif(x, min, max, int(log), out=out)
    _capture.check()
    return result

def punif(q, min=0.0, max=1.0, lower_tail=True, log=False, out=None):
    """punif backed by R 4.5.2 nmath."""
    with _errstate.capture("punif") as _capture:
        result = _ufuncs.punif(q, min, max, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qunif(p, min=0.0, max=1.0, lower_tail=True, log=False, out=None):
    """qunif backed by R 4.5.2 nmath."""
    with _errstate.capture("qunif") as _capture:
        result = _ufuncs.qunif(p, min, max, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def runif(n, min=0.0, max=1.0):
    """runif backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("runif") as _capture:
        result = _rng.draw(_ufuncs.runif, n, min, max)
    _capture.check()
    return result

def dgamma(x, shape, rate=1.0, scale=None, log=False, out=None):
    """dgamma backed by R 4.5.2 nmath."""
    scale = _dispatch.resolve_rate_scale(rate, scale)
    with _errstate.capture("dgamma") as _capture:
        result = _ufuncs.dgamma(x, shape, scale, int(log), out=out)
    _capture.check()
    return result

def pgamma(q, shape, rate=1.0, scale=None, lower_tail=True, log=False, out=None):
    """pgamma backed by R 4.5.2 nmath."""
    scale = _dispatch.resolve_rate_scale(rate, scale)
    with _errstate.capture("pgamma") as _capture:
        result = _ufuncs.pgamma(q, shape, scale, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qgamma(p, shape, rate=1.0, scale=None, lower_tail=True, log=False, out=None):
    """qgamma backed by R 4.5.2 nmath."""
    scale = _dispatch.resolve_rate_scale(rate, scale)
    with _errstate.capture("qgamma") as _capture:
        result = _ufuncs.qgamma(p, shape, scale, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rgamma(n, shape, rate=1.0, scale=None):
    """rgamma backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    scale = _dispatch.resolve_rate_scale(rate, scale)
    with _errstate.capture("rgamma") as _capture:
        result = _rng.draw(_ufuncs.rgamma, n, shape, scale)
    _capture.check()
    return result

def dbeta(x, shape1, shape2, ncp=None, log=False, out=None):
    """dbeta backed by R 4.5.2 nmath."""
    with _errstate.capture("dbeta") as _capture:
        if ncp is None:
            result = _ufuncs.dbeta(x, shape1, shape2, int(log), out=out)
        else:
            result = _ufuncs.dnbeta(x, shape1, shape2, ncp, int(log), out=out)
    _capture.check()
    return result

def pbeta(q, shape1, shape2, ncp=None, lower_tail=True, log=False, out=None):
    """pbeta backed by R 4.5.2 nmath."""
    with _errstate.capture("pbeta") as _capture:
        if ncp is None:
            result = _ufuncs.pbeta(q, shape1, shape2, int(lower_tail), int(log), out=out)
        else:
            result = _ufuncs.pnbeta(q, shape1, shape2, ncp, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qbeta(p, shape1, shape2, ncp=None, lower_tail=True, log=False, out=None):
    """qbeta backed by R 4.5.2 nmath."""
    with _errstate.capture("qbeta") as _capture:
        if ncp is None:
            result = _ufuncs.qbeta(p, shape1, shape2, int(lower_tail), int(log), out=out)
        else:
            result = _ufuncs.qnbeta(p, shape1, shape2, ncp, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rbeta(n, shape1, shape2, ncp=None):
    """rbeta backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    if ncp is not None:
        with _rng.locked():
            x = rchisq(n, 2 * shape1, ncp=ncp)
            return x / (x + rchisq(n, 2 * shape2))
    with _errstate.capture("rbeta") as _capture:
        result = _rng.draw(_ufuncs.rbeta, n, shape1, shape2)
    _capture.check()
    return result

def dlnorm(x, meanlog=0.0, sdlog=1.0, log=False, out=None):
    """dlnorm backed by R 4.5.2 nmath."""
    with _errstate.capture("dlnorm") as _capture:
        result = _ufuncs.dlnorm(x, meanlog, sdlog, int(log), out=out)
    _capture.check()
    return result

def plnorm(q, meanlog=0.0, sdlog=1.0, lower_tail=True, log=False, out=None):
    """plnorm backed by R 4.5.2 nmath."""
    with _errstate.capture("plnorm") as _capture:
        result = _ufuncs.plnorm(q, meanlog, sdlog, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qlnorm(p, meanlog=0.0, sdlog=1.0, lower_tail=True, log=False, out=None):
    """qlnorm backed by R 4.5.2 nmath."""
    with _errstate.capture("qlnorm") as _capture:
        result = _ufuncs.qlnorm(p, meanlog, sdlog, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rlnorm(n, meanlog=0.0, sdlog=1.0):
    """rlnorm backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rlnorm") as _capture:
        result = _rng.draw(_ufuncs.rlnorm, n, meanlog, sdlog)
    _capture.check()
    return result

def dchisq(x, df, ncp=None, log=False, out=None):
    """dchisq backed by R 4.5.2 nmath."""
    with _errstate.capture("dchisq") as _capture:
        if ncp is None:
            result = _ufuncs.dchisq(x, df, int(log), out=out)
        else:
            result = _ufuncs.dnchisq(x, df, ncp, int(log), out=out)
    _capture.check()
    return result

def pchisq(q, df, ncp=None, lower_tail=True, log=False, out=None):
    """pchisq backed by R 4.5.2 nmath."""
    with _errstate.capture("pchisq") as _capture:
        if ncp is None:
            result = _ufuncs.pchisq(q, df, int(lower_tail), int(log), out=out)
        else:
            result = _ufuncs.pnchisq(q, df, ncp, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qchisq(p, df, ncp=None, lower_tail=True, log=False, out=None):
    """qchisq backed by R 4.5.2 nmath."""
    with _errstate.capture("qchisq") as _capture:
        if ncp is None:
            result = _ufuncs.qchisq(p, df, int(lower_tail), int(log), out=out)
        else:
            result = _ufuncs.qnchisq(p, df, ncp, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rchisq(n, df, ncp=None):
    """rchisq backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rchisq") as _capture:
        if ncp is None:
            result = _rng.draw(_ufuncs.rchisq, n, df)
        else:
            result = _rng.draw(_ufuncs.rnchisq, n, df, ncp)
    _capture.check()
    return result

def df(x, df1, df2, ncp=None, log=False, out=None):
    """df backed by R 4.5.2 nmath."""
    with _errstate.capture("df") as _capture:
        if ncp is None:
            result = _ufuncs.df(x, df1, df2, int(log), out=out)
        else:
            result = _ufuncs.dnf(x, df1, df2, ncp, int(log), out=out)
    _capture.check()
    return result

def pf(q, df1, df2, ncp=None, lower_tail=True, log=False, out=None):
    """pf backed by R 4.5.2 nmath."""
    with _errstate.capture("pf") as _capture:
        if ncp is None:
            result = _ufuncs.pf(q, df1, df2, int(lower_tail), int(log), out=out)
        else:
            result = _ufuncs.pnf(q, df1, df2, ncp, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qf(p, df1, df2, ncp=None, lower_tail=True, log=False, out=None):
    """qf backed by R 4.5.2 nmath."""
    with _errstate.capture("qf") as _capture:
        if ncp is None:
            result = _ufuncs.qf(p, df1, df2, int(lower_tail), int(log), out=out)
        else:
            result = _ufuncs.qnf(p, df1, df2, ncp, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rf(n, df1, df2, ncp=None):
    """rf backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    if ncp is not None:
        with _rng.locked():
            return (rchisq(n, df1, ncp=ncp) / df1) / (rchisq(n, df2) / df2)
    with _errstate.capture("rf") as _capture:
        result = _rng.draw(_ufuncs.rf, n, df1, df2)
    _capture.check()
    return result

def dt(x, df, ncp=None, log=False, out=None):
    """dt backed by R 4.5.2 nmath."""
    with _errstate.capture("dt") as _capture:
        if ncp is None:
            result = _ufuncs.dt(x, df, int(log), out=out)
        else:
            result = _ufuncs.dnt(x, df, ncp, int(log), out=out)
    _capture.check()
    return result

def pt(q, df, ncp=None, lower_tail=True, log=False, out=None):
    """pt backed by R 4.5.2 nmath."""
    with _errstate.capture("pt") as _capture:
        if ncp is None:
            result = _ufuncs.pt(q, df, int(lower_tail), int(log), out=out)
        else:
            result = _ufuncs.pnt(q, df, ncp, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qt(p, df, ncp=None, lower_tail=True, log=False, out=None):
    """qt backed by R 4.5.2 nmath."""
    with _errstate.capture("qt") as _capture:
        if ncp is None:
            result = _ufuncs.qt(p, df, int(lower_tail), int(log), out=out)
        else:
            result = _ufuncs.qnt(p, df, ncp, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rt(n, df, ncp=None):
    """rt backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    if ncp is not None:
        with _rng.locked():
            return rnorm(n, ncp) / _dispatch.sqrt(rchisq(n, df) / df)
    with _errstate.capture("rt") as _capture:
        result = _rng.draw(_ufuncs.rt, n, df)
    _capture.check()
    return result

def dbinom(x, size, prob, log=False, out=None):
    """dbinom backed by R 4.5.2 nmath."""
    with _errstate.capture("dbinom") as _capture:
        result = _ufuncs.dbinom(x, size, prob, int(log), out=out)
    _capture.check()
    return result

def pbinom(q, size, prob, lower_tail=True, log=False, out=None):
    """pbinom backed by R 4.5.2 nmath."""
    with _errstate.capture("pbinom") as _capture:
        result = _ufuncs.pbinom(q, size, prob, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qbinom(p, size, prob, lower_tail=True, log=False, out=None):
    """qbinom backed by R 4.5.2 nmath."""
    with _errstate.capture("qbinom") as _capture:
        result = _ufuncs.qbinom(p, size, prob, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rbinom(n, size, prob):
    """rbinom backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rbinom") as _capture:
        result = _rng.draw(_ufuncs.rbinom, n, size, prob)
    _capture.check()
    return result

def dcauchy(x, location=0.0, scale=1.0, log=False, out=None):
    """dcauchy backed by R 4.5.2 nmath."""
    with _errstate.capture("dcauchy") as _capture:
        result = _ufuncs.dcauchy(x, location, scale, int(log), out=out)
    _capture.check()
    return result

def pcauchy(q, location=0.0, scale=1.0, lower_tail=True, log=False, out=None):
    """pcauchy backed by R 4.5.2 nmath."""
    with _errstate.capture("pcauchy") as _capture:
        result = _ufuncs.pcauchy(q, location, scale, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qcauchy(p, location=0.0, scale=1.0, lower_tail=True, log=False, out=None):
    """qcauchy backed by R 4.5.2 nmath."""
    with _errstate.capture("qcauchy") as _capture:
        result = _ufuncs.qcauchy(p, location, scale, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rcauchy(n, location=0.0, scale=1.0):
    """rcauchy backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rcauchy") as _capture:
        result = _rng.draw(_ufuncs.rcauchy, n, location, scale)
    _capture.check()
    return result

def dexp(x, rate=1.0, log=False, out=None):
    """dexp backed by R 4.5.2 nmath."""
    rate = _dispatch.reciprocal(rate)
    with _errstate.capture("dexp") as _capture:
        result = _ufuncs.dexp(x, rate, int(log), out=out)
    _capture.check()
    return result

def pexp(q, rate=1.0, lower_tail=True, log=False, out=None):
    """pexp backed by R 4.5.2 nmath."""
    rate = _dispatch.reciprocal(rate)
    with _errstate.capture("pexp") as _capture:
        result = _ufuncs.pexp(q, rate, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qexp(p, rate=1.0, lower_tail=True, log=False, out=None):
    """qexp backed by R 4.5.2 nmath."""
    rate = _dispatch.reciprocal(rate)
    with _errstate.capture("qexp") as _capture:
        result = _ufuncs.qexp(p, rate, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rexp(n, rate=1.0):
    """rexp backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    rate = _dispatch.reciprocal(rate)
    with _errstate.capture("rexp") as _capture:
        result = _rng.draw(_ufuncs.rexp, n, rate)
    _capture.check()
    return result

def dgeom(x, prob, log=False, out=None):
    """dgeom backed by R 4.5.2 nmath."""
    with _errstate.capture("dgeom") as _capture:
        result = _ufuncs.dgeom(x, prob, int(log), out=out)
    _capture.check()
    return result

def pgeom(q, prob, lower_tail=True, log=False, out=None):
    """pgeom backed by R 4.5.2 nmath."""
    with _errstate.capture("pgeom") as _capture:
        result = _ufuncs.pgeom(q, prob, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qgeom(p, prob, lower_tail=True, log=False, out=None):
    """qgeom backed by R 4.5.2 nmath."""
    with _errstate.capture("qgeom") as _capture:
        result = _ufuncs.qgeom(p, prob, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rgeom(n, prob):
    """rgeom backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rgeom") as _capture:
        result = _rng.draw(_ufuncs.rgeom, n, prob)
    _capture.check()
    return result

def dhyper(x, m, n, k, log=False, out=None):
    """dhyper backed by R 4.5.2 nmath."""
    with _errstate.capture("dhyper") as _capture:
        result = _ufuncs.dhyper(x, m, n, k, int(log), out=out)
    _capture.check()
    return result

def phyper(q, m, n, k, lower_tail=True, log=False, out=None):
    """phyper backed by R 4.5.2 nmath."""
    with _errstate.capture("phyper") as _capture:
        result = _ufuncs.phyper(q, m, n, k, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qhyper(p, m, n, k, lower_tail=True, log=False, out=None):
    """qhyper backed by R 4.5.2 nmath."""
    with _errstate.capture("qhyper") as _capture:
        result = _ufuncs.qhyper(p, m, n, k, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rhyper(nn, m, n, k):
    """rhyper backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rhyper") as _capture:
        result = _rng.draw(_ufuncs.rhyper, nn, m, n, k)
    _capture.check()
    return result

def dnbinom(x, size, prob=None, mu=None, log=False, out=None):
    """dnbinom backed by R 4.5.2 nmath."""
    with _errstate.capture("dnbinom") as _capture:
        parameterization = _dispatch.resolve_prob_mu(prob, mu)
        if parameterization == 'prob':
            result = _ufuncs.dnbinom(x, size, prob, int(log), out=out)
        else:
            result = _ufuncs.dnbinom_mu(x, size, mu, int(log), out=out)
    _capture.check()
    return result

def pnbinom(q, size, prob=None, mu=None, lower_tail=True, log=False, out=None):
    """pnbinom backed by R 4.5.2 nmath."""
    with _errstate.capture("pnbinom") as _capture:
        parameterization = _dispatch.resolve_prob_mu(prob, mu)
        if parameterization == 'prob':
            result = _ufuncs.pnbinom(q, size, prob, int(lower_tail), int(log), out=out)
        else:
            result = _ufuncs.pnbinom_mu(q, size, mu, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qnbinom(p, size, prob=None, mu=None, lower_tail=True, log=False, out=None):
    """qnbinom backed by R 4.5.2 nmath."""
    with _errstate.capture("qnbinom") as _capture:
        parameterization = _dispatch.resolve_prob_mu(prob, mu)
        if parameterization == 'prob':
            result = _ufuncs.qnbinom(p, size, prob, int(lower_tail), int(log), out=out)
        else:
            result = _ufuncs.qnbinom_mu(p, size, mu, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rnbinom(n, size, prob=None, mu=None):
    """rnbinom backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rnbinom") as _capture:
        parameterization = _dispatch.resolve_prob_mu(prob, mu)
        if parameterization == 'prob':
            result = _rng.draw(_ufuncs.rnbinom, n, size, prob)
        else:
            result = _rng.draw(_ufuncs.rnbinom_mu, n, size, mu)
    _capture.check()
    return result

def dpois(x, lambda_, log=False, out=None):
    """dpois backed by R 4.5.2 nmath."""
    with _errstate.capture("dpois") as _capture:
        result = _ufuncs.dpois(x, lambda_, int(log), out=out)
    _capture.check()
    return result

def ppois(q, lambda_, lower_tail=True, log=False, out=None):
    """ppois backed by R 4.5.2 nmath."""
    with _errstate.capture("ppois") as _capture:
        result = _ufuncs.ppois(q, lambda_, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qpois(p, lambda_, lower_tail=True, log=False, out=None):
    """qpois backed by R 4.5.2 nmath."""
    with _errstate.capture("qpois") as _capture:
        result = _ufuncs.qpois(p, lambda_, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rpois(n, lambda_):
    """rpois backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rpois") as _capture:
        result = _rng.draw(_ufuncs.rpois, n, lambda_)
    _capture.check()
    return result

def dweibull(x, shape, scale=1.0, log=False, out=None):
    """dweibull backed by R 4.5.2 nmath."""
    with _errstate.capture("dweibull") as _capture:
        result = _ufuncs.dweibull(x, shape, scale, int(log), out=out)
    _capture.check()
    return result

def pweibull(q, shape, scale=1.0, lower_tail=True, log=False, out=None):
    """pweibull backed by R 4.5.2 nmath."""
    with _errstate.capture("pweibull") as _capture:
        result = _ufuncs.pweibull(q, shape, scale, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qweibull(p, shape, scale=1.0, lower_tail=True, log=False, out=None):
    """qweibull backed by R 4.5.2 nmath."""
    with _errstate.capture("qweibull") as _capture:
        result = _ufuncs.qweibull(p, shape, scale, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rweibull(n, shape, scale=1.0):
    """rweibull backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rweibull") as _capture:
        result = _rng.draw(_ufuncs.rweibull, n, shape, scale)
    _capture.check()
    return result

def dlogis(x, location=0.0, scale=1.0, log=False, out=None):
    """dlogis backed by R 4.5.2 nmath."""
    with _errstate.capture("dlogis") as _capture:
        result = _ufuncs.dlogis(x, location, scale, int(log), out=out)
    _capture.check()
    return result

def plogis(q, location=0.0, scale=1.0, lower_tail=True, log=False, out=None):
    """plogis backed by R 4.5.2 nmath."""
    with _errstate.capture("plogis") as _capture:
        result = _ufuncs.plogis(q, location, scale, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qlogis(p, location=0.0, scale=1.0, lower_tail=True, log=False, out=None):
    """qlogis backed by R 4.5.2 nmath."""
    with _errstate.capture("qlogis") as _capture:
        result = _ufuncs.qlogis(p, location, scale, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rlogis(n, location=0.0, scale=1.0):
    """rlogis backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rlogis") as _capture:
        result = _rng.draw(_ufuncs.rlogis, n, location, scale)
    _capture.check()
    return result

def dwilcox(x, m, n, log=False, out=None):
    """dwilcox backed by R 4.5.2 nmath."""
    with _errstate.capture("dwilcox") as _capture:
        result = _ufuncs.dwilcox(x, m, n, int(log), out=out)
    _capture.check()
    return result

def pwilcox(q, m, n, lower_tail=True, log=False, out=None):
    """pwilcox backed by R 4.5.2 nmath."""
    with _errstate.capture("pwilcox") as _capture:
        result = _ufuncs.pwilcox(q, m, n, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qwilcox(p, m, n, lower_tail=True, log=False, out=None):
    """qwilcox backed by R 4.5.2 nmath."""
    with _errstate.capture("qwilcox") as _capture:
        result = _ufuncs.qwilcox(p, m, n, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rwilcox(nn, m, n):
    """rwilcox backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rwilcox") as _capture:
        result = _rng.draw(_ufuncs.rwilcox, nn, m, n)
    _capture.check()
    return result

def dsignrank(x, n, log=False, out=None):
    """dsignrank backed by R 4.5.2 nmath."""
    with _errstate.capture("dsignrank") as _capture:
        result = _ufuncs.dsignrank(x, n, int(log), out=out)
    _capture.check()
    return result

def psignrank(q, n, lower_tail=True, log=False, out=None):
    """psignrank backed by R 4.5.2 nmath."""
    with _errstate.capture("psignrank") as _capture:
        result = _ufuncs.psignrank(q, n, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qsignrank(p, n, lower_tail=True, log=False, out=None):
    """qsignrank backed by R 4.5.2 nmath."""
    with _errstate.capture("qsignrank") as _capture:
        result = _ufuncs.qsignrank(p, n, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def rsignrank(nn, n):
    """rsignrank backed by R 4.5.2 nmath; does not reproduce R's set.seed() stream."""
    with _errstate.capture("rsignrank") as _capture:
        result = _rng.draw(_ufuncs.rsignrank, nn, n)
    _capture.check()
    return result

def ptukey(q, nmeans, df, nranges=1.0, lower_tail=True, log=False, out=None):
    """ptukey backed by R 4.5.2 nmath."""
    with _errstate.capture("ptukey") as _capture:
        result = _ufuncs.ptukey(q, nranges, nmeans, df, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def qtukey(p, nmeans, df, nranges=1.0, lower_tail=True, log=False, out=None):
    """qtukey backed by R 4.5.2 nmath."""
    with _errstate.capture("qtukey") as _capture:
        result = _ufuncs.qtukey(p, nranges, nmeans, df, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

def gammafn(x, out=None):
    """gammafn backed by R 4.5.2 nmath R: gamma(x)."""
    with _errstate.capture("gammafn") as _capture:
        result = _ufuncs.gammafn(x, out=out)
    _capture.check()
    return result

def lgammafn(x, out=None):
    """lgammafn backed by R 4.5.2 nmath R: lgamma(x)."""
    with _errstate.capture("lgammafn") as _capture:
        result = _ufuncs.lgammafn(x, out=out)
    _capture.check()
    return result

def digamma(x, out=None):
    """digamma backed by R 4.5.2 nmath R: digamma(x)."""
    with _errstate.capture("digamma") as _capture:
        result = _ufuncs.digamma(x, out=out)
    _capture.check()
    return result

def trigamma(x, out=None):
    """trigamma backed by R 4.5.2 nmath R: trigamma(x)."""
    with _errstate.capture("trigamma") as _capture:
        result = _ufuncs.trigamma(x, out=out)
    _capture.check()
    return result

def tetragamma(x, out=None):
    """tetragamma backed by R 4.5.2 nmath R: psigamma(x, 2)."""
    with _errstate.capture("tetragamma") as _capture:
        result = _ufuncs.tetragamma(x, out=out)
    _capture.check()
    return result

def pentagamma(x, out=None):
    """pentagamma backed by R 4.5.2 nmath R: psigamma(x, 3)."""
    with _errstate.capture("pentagamma") as _capture:
        result = _ufuncs.pentagamma(x, out=out)
    _capture.check()
    return result

def psigamma(x, deriv=0.0, out=None):
    """psigamma backed by R 4.5.2 nmath R: psigamma(x, deriv)."""
    with _errstate.capture("psigamma") as _capture:
        result = _ufuncs.psigamma(x, deriv, out=out)
    _capture.check()
    return result

def beta(a, b, out=None):
    """beta backed by R 4.5.2 nmath R: beta(a, b)."""
    with _errstate.capture("beta") as _capture:
        result = _ufuncs.beta(a, b, out=out)
    _capture.check()
    return result

def lbeta(a, b, out=None):
    """lbeta backed by R 4.5.2 nmath R: lbeta(a, b)."""
    with _errstate.capture("lbeta") as _capture:
        result = _ufuncs.lbeta(a, b, out=out)
    _capture.check()
    return result

def choose(n, k, out=None):
    """choose backed by R 4.5.2 nmath R: choose(n, k)."""
    with _errstate.capture("choose") as _capture:
        result = _ufuncs.choose(n, k, out=out)
    _capture.check()
    return result

def lchoose(n, k, out=None):
    """lchoose backed by R 4.5.2 nmath R: lchoose(n, k)."""
    with _errstate.capture("lchoose") as _capture:
        result = _ufuncs.lchoose(n, k, out=out)
    _capture.check()
    return result

def bessel_j(x, nu, out=None):
    """bessel_j backed by R 4.5.2 nmath R: besselJ(x, nu)."""
    with _errstate.capture("bessel_j") as _capture:
        result = _ufuncs.bessel_j(x, nu, out=out)
    _capture.check()
    return result

def bessel_y(x, nu, out=None):
    """bessel_y backed by R 4.5.2 nmath R: besselY(x, nu)."""
    with _errstate.capture("bessel_y") as _capture:
        result = _ufuncs.bessel_y(x, nu, out=out)
    _capture.check()
    return result

def bessel_i(x, nu, expon_scaled=False, out=None):
    """bessel_i backed by R 4.5.2 nmath R: besselI(x, nu, expon.scaled)."""
    expon_scaled = 2.0 if expon_scaled else 1.0
    with _errstate.capture("bessel_i") as _capture:
        result = _ufuncs.bessel_i(x, nu, expon_scaled, out=out)
    _capture.check()
    return result

def bessel_k(x, nu, expon_scaled=False, out=None):
    """bessel_k backed by R 4.5.2 nmath R: besselK(x, nu, expon.scaled)."""
    expon_scaled = 2.0 if expon_scaled else 1.0
    with _errstate.capture("bessel_k") as _capture:
        result = _ufuncs.bessel_k(x, nu, expon_scaled, out=out)
    _capture.check()
    return result

def log1pmx(x, out=None):
    """log(1+x) - x, accurate for small x."""
    with _errstate.capture("log1pmx") as _capture:
        result = _ufuncs.log1pmx(x, out=out)
    _capture.check()
    return result

def log1pexp(x, out=None):
    """log(1 + exp(x)) without overflow."""
    with _errstate.capture("log1pexp") as _capture:
        result = _ufuncs.log1pexp(x, out=out)
    _capture.check()
    return result

def lgamma1p(x, out=None):
    """lgamma(1+x), accurate for small x."""
    with _errstate.capture("lgamma1p") as _capture:
        result = _ufuncs.lgamma1p(x, out=out)
    _capture.check()
    return result

def logspace_add(logx, logy, out=None):
    """log(exp(logx) + exp(logy))."""
    with _errstate.capture("logspace_add") as _capture:
        result = _ufuncs.logspace_add(logx, logy, out=out)
    _capture.check()
    return result

def logspace_sub(logx, logy, out=None):
    """log(exp(logx) - exp(logy))."""
    with _errstate.capture("logspace_sub") as _capture:
        result = _ufuncs.logspace_sub(logx, logy, out=out)
    _capture.check()
    return result

def cospi(x, out=None):
    """cos(pi*x), exact at half-integers."""
    with _errstate.capture("cospi") as _capture:
        result = _ufuncs.cospi(x, out=out)
    _capture.check()
    return result

def sinpi(x, out=None):
    """sin(pi*x), exact at integers."""
    with _errstate.capture("sinpi") as _capture:
        result = _ufuncs.sinpi(x, out=out)
    _capture.check()
    return result

def tanpi(x, out=None):
    """tan(pi*x)."""
    with _errstate.capture("tanpi") as _capture:
        result = _ufuncs.tanpi(x, out=out)
    _capture.check()
    return result

def fprec(x, digits, out=None):
    """round x to `digits` significant digits."""
    with _errstate.capture("fprec") as _capture:
        result = _ufuncs.fprec(x, digits, out=out)
    _capture.check()
    return result

def fround(x, digits, out=None):
    """R's round(), banker's rounding."""
    with _errstate.capture("fround") as _capture:
        result = _ufuncs.fround(x, digits, out=out)
    _capture.check()
    return result

def fsign(x, y, out=None):
    """|x| * sign(y)."""
    with _errstate.capture("fsign") as _capture:
        result = _ufuncs.fsign(x, y, out=out)
    _capture.check()
    return result

def ftrunc(x, out=None):
    """truncate toward zero."""
    with _errstate.capture("ftrunc") as _capture:
        result = _ufuncs.ftrunc(x, out=out)
    _capture.check()
    return result

def sign(x, out=None):
    """-1, 0, or 1."""
    with _errstate.capture("sign") as _capture:
        result = _ufuncs.sign(x, out=out)
    _capture.check()
    return result

__all__ = ['dnorm', 'pnorm', 'qnorm', 'rnorm', 'dunif', 'punif', 'qunif', 'runif', 'dgamma', 'pgamma', 'qgamma', 'rgamma', 'dbeta', 'pbeta', 'qbeta', 'rbeta', 'dlnorm', 'plnorm', 'qlnorm', 'rlnorm', 'dchisq', 'pchisq', 'qchisq', 'rchisq', 'df', 'pf', 'qf', 'rf', 'dt', 'pt', 'qt', 'rt', 'dbinom', 'pbinom', 'qbinom', 'rbinom', 'dcauchy', 'pcauchy', 'qcauchy', 'rcauchy', 'dexp', 'pexp', 'qexp', 'rexp', 'dgeom', 'pgeom', 'qgeom', 'rgeom', 'dhyper', 'phyper', 'qhyper', 'rhyper', 'dnbinom', 'pnbinom', 'qnbinom', 'rnbinom', 'dpois', 'ppois', 'qpois', 'rpois', 'dweibull', 'pweibull', 'qweibull', 'rweibull', 'dlogis', 'plogis', 'qlogis', 'rlogis', 'dwilcox', 'pwilcox', 'qwilcox', 'rwilcox', 'dsignrank', 'psignrank', 'qsignrank', 'rsignrank', 'ptukey', 'qtukey', 'gammafn', 'lgammafn', 'digamma', 'trigamma', 'tetragamma', 'pentagamma', 'psigamma', 'beta', 'lbeta', 'choose', 'lchoose', 'bessel_j', 'bessel_y', 'bessel_i', 'bessel_k', 'log1pmx', 'log1pexp', 'lgamma1p', 'logspace_add', 'logspace_sub', 'cospi', 'sinpi', 'tanpi', 'fprec', 'fround', 'fsign', 'ftrunc', 'sign']
