# GENERATED by tools/regen.py -- do not edit.
from __future__ import annotations

from . import _errstate, _ufuncs

def ppois(q, lambda_, lower_tail=True, log=False, out=None):
    """Poisson distribution function. R: ppois(q, lambda, lower.tail, log.p)."""
    with _errstate.capture("ppois") as _capture:
        result = _ufuncs.ppois(q, lambda_, int(lower_tail), int(log), out=out)
    _capture.check()
    return result

__all__ = ['ppois']
