# GENERATED by tools/regen.py -- do not edit.
from typing import Any
import numpy as np

def ppois(q: Any, lambda_: Any, lower_tail: bool = True, log: bool = False, out: Any = None) -> np.float64 | np.ndarray[Any, Any]: ...
