from typing import Any

def _clear_error() -> None: ...
def _take_error() -> int: ...
def _force_allocation_failure() -> None: ...
def _set_seed(i1: int, i2: int) -> None: ...
def _get_seed() -> tuple[int, int]: ...
def _free_caches() -> None: ...
def __getattr__(name: str) -> Any: ...

