from typing import Any

def _clear_error() -> None: ...
def _take_error() -> int: ...
def _force_allocation_failure() -> None: ...
def _set_seed(i1: int, i2: int) -> None: ...
def _get_seed() -> tuple[int, int]: ...
def _acquire_rng_lock() -> None: ...
def _release_rng_lock() -> None: ...
def _pnorm_both_array(x: Any, log: int) -> Any: ...
def _lgammafn_sign_array(x: Any) -> Any: ...
def _logspace_sum_last(values: Any) -> Any: ...
def _rmultinom_rows(n: int, size: int, prob: Any) -> Any: ...
def _free_caches() -> None: ...
def __getattr__(name: str) -> Any: ...
