/* GENERATED by tools/regen.py -- do not edit. */
#define PY_SSIZE_T_CLEAN
#define NPY_NO_DEPRECATED_API NPY_1_25_API_VERSION
#include <Python.h>
#include <numpy/arrayobject.h>
#include <numpy/ufuncobject.h>
#include <Rmath.h>
#include "accudist_shim.h"

extern void wilcox_free(void);
extern void signrank_free(void);
extern PyThread_type_lock accudist_cache_lock;
extern PyThread_type_lock accudist_rng_lock;

static void
ppois_loop(char **args, const npy_intp *dims, const npy_intp *steps, void *data)
{
    npy_intp n = dims[0];
    (void)data;
    for (npy_intp i = 0; i < n; i++) {
        double q = *(double *)(args[0] + i * steps[0]);
        double lambda = *(double *)(args[1] + i * steps[1]);
        long lower_tail = *(long *)(args[2] + i * steps[2]);
        long log = *(long *)(args[3] + i * steps[3]);
        *(double *)(args[4] + i * steps[4]) =
            ppois(q, lambda, (int)lower_tail, (int)log);
    }
}

static PyUFuncGenericFunction ppois_funcs[1] = {ppois_loop};
static void *ppois_data[1] = {NULL};
static char ppois_types[] = {NPY_DOUBLE, NPY_DOUBLE, NPY_LONG, NPY_LONG, NPY_DOUBLE};

static PyObject *
py_clear_error(PyObject *self, PyObject *ignored)
{
    (void)self;
    (void)ignored;
    accudist_clear_error();
    Py_RETURN_NONE;
}

static PyObject *
py_take_error(PyObject *self, PyObject *ignored)
{
    (void)self;
    (void)ignored;
    return PyLong_FromUnsignedLong(accudist_take_error());
}

static PyObject *
py_force_allocation_failure(PyObject *self, PyObject *ignored)
{
    (void)self;
    (void)ignored;
    accudist_fatal("forced allocation failure: %d", 1);
    Py_RETURN_NONE;
}

static PyObject *
py_free_caches(PyObject *self, PyObject *ignored)
{
    (void)self;
    (void)ignored;
    PyThread_acquire_lock(accudist_cache_lock, WAIT_LOCK);
    wilcox_free();
    signrank_free();
    PyThread_release_lock(accudist_cache_lock);
    Py_RETURN_NONE;
}

static PyMethodDef module_methods[] = {
    {"_clear_error", py_clear_error, METH_NOARGS, NULL},
    {"_take_error", py_take_error, METH_NOARGS, NULL},
    {"_force_allocation_failure", py_force_allocation_failure, METH_NOARGS, NULL},
    {"_free_caches", py_free_caches, METH_NOARGS, NULL},
    {NULL, NULL, 0, NULL}
};

static void
module_free(void *module)
{
    (void)module;
    if (accudist_cache_lock != NULL) {
        PyThread_acquire_lock(accudist_cache_lock, WAIT_LOCK);
        wilcox_free();
        signrank_free();
        PyThread_release_lock(accudist_cache_lock);
    }
    accudist_free_locks();
}

static struct PyModuleDef module_def = {
    PyModuleDef_HEAD_INIT,
    "_ufuncs",
    "Generated NumPy ufuncs backed by R nmath.",
    -1,
    module_methods,
    NULL,
    NULL,
    NULL,
    module_free
};

PyMODINIT_FUNC
PyInit__ufuncs(void)
{
    PyObject *module;
    import_array();
    import_umath();
    if (accudist_init_locks() < 0) {
        PyErr_NoMemory();
        return NULL;
    }
    module = PyModule_Create(&module_def);
    if (module == NULL) {
        accudist_free_locks();
        return NULL;
    }
    {
        PyObject *ufunc = PyUFunc_FromFuncAndData(
            ppois_funcs, ppois_data, ppois_types,
            1, 4, 1, PyUFunc_None,
            "ppois", "Raw R nmath ppois ufunc.", 0
        );
        if (ufunc == NULL || PyModule_AddObject(module, "ppois", ufunc) < 0) {
            Py_XDECREF(ufunc);
            Py_DECREF(module);
            return NULL;
        }
    }
    return module;
}
