# GENERATED by tools/regen.py from functions.toml -- do not edit.
"""Raw 1:1 access to the vendored ``Rmath.h`` symbols.

Every function here is the NumPy ufunc that wraps the C symbol of the same name:
positional arguments in **C order**, ``lower_tail``/``log_p`` flags as trailing
0/1 inputs, no defaults, no ``ncp``/``mu``/``scale`` dispatch, and no error
translation (the thread-local nmath error word is left untouched). Prefer the
public :mod:`accudist` API; use this when you need e.g. ``pnchisq`` or
``dbinom_raw`` directly.

Note that ``r*`` functions here draw from the global generator without taking
the RNG lock; use :class:`accudist.RNG` for thread-safe draws.
"""

from ._ufuncs import (
    bessel_i,
    bessel_j,
    bessel_k,
    bessel_y,
    beta,
    choose,
    cospi,
    dbeta,
    dbinom,
    dbinom_raw,
    dcauchy,
    dchisq,
    dexp,
    df,
    dgamma,
    dgeom,
    dhyper,
    digamma,
    dlnorm,
    dlogis,
    dnbeta,
    dnbinom,
    dnbinom_mu,
    dnchisq,
    dnf,
    dnorm,
    dnt,
    dpois,
    dpois_raw,
    dsignrank,
    dt,
    dunif,
    dweibull,
    dwilcox,
    fprec,
    fround,
    fsign,
    ftrunc,
    gammafn,
    lbeta,
    lchoose,
    lgamma1p,
    lgammafn,
    log1mexp,
    log1pexp,
    log1pmx,
    logspace_add,
    logspace_sub,
    pbeta,
    pbinom,
    pcauchy,
    pchisq,
    pentagamma,
    pexp,
    pf,
    pgamma,
    pgeom,
    phyper,
    plnorm,
    plogis,
    pnbeta,
    pnbinom,
    pnbinom_mu,
    pnchisq,
    pnf,
    pnorm,
    pnt,
    pow1p,
    ppois,
    psigamma,
    psignrank,
    pt,
    ptukey,
    punif,
    pweibull,
    pwilcox,
    qbeta,
    qbinom,
    qcauchy,
    qchisq,
    qexp,
    qf,
    qgamma,
    qgeom,
    qhyper,
    qlnorm,
    qlogis,
    qnbeta,
    qnbinom,
    qnbinom_mu,
    qnchisq,
    qnf,
    qnorm,
    qnt,
    qpois,
    qsignrank,
    qt,
    qtukey,
    qunif,
    qweibull,
    qwilcox,
    rbeta,
    rbinom,
    rcauchy,
    rchisq,
    rexp,
    rf,
    rgamma,
    rgeom,
    rhyper,
    rlnorm,
    rlogis,
    rnbinom,
    rnbinom_mu,
    rnchisq,
    rnorm,
    rpois,
    rsignrank,
    rt,
    runif,
    rweibull,
    rwilcox,
    sign,
    sinpi,
    tanpi,
    tetragamma,
    trigamma,
)

__all__ = [
    'bessel_i',
    'bessel_j',
    'bessel_k',
    'bessel_y',
    'beta',
    'choose',
    'cospi',
    'dbeta',
    'dbinom',
    'dbinom_raw',
    'dcauchy',
    'dchisq',
    'dexp',
    'df',
    'dgamma',
    'dgeom',
    'dhyper',
    'digamma',
    'dlnorm',
    'dlogis',
    'dnbeta',
    'dnbinom',
    'dnbinom_mu',
    'dnchisq',
    'dnf',
    'dnorm',
    'dnt',
    'dpois',
    'dpois_raw',
    'dsignrank',
    'dt',
    'dunif',
    'dweibull',
    'dwilcox',
    'fprec',
    'fround',
    'fsign',
    'ftrunc',
    'gammafn',
    'lbeta',
    'lchoose',
    'lgamma1p',
    'lgammafn',
    'log1mexp',
    'log1pexp',
    'log1pmx',
    'logspace_add',
    'logspace_sub',
    'pbeta',
    'pbinom',
    'pcauchy',
    'pchisq',
    'pentagamma',
    'pexp',
    'pf',
    'pgamma',
    'pgeom',
    'phyper',
    'plnorm',
    'plogis',
    'pnbeta',
    'pnbinom',
    'pnbinom_mu',
    'pnchisq',
    'pnf',
    'pnorm',
    'pnt',
    'pow1p',
    'ppois',
    'psigamma',
    'psignrank',
    'pt',
    'ptukey',
    'punif',
    'pweibull',
    'pwilcox',
    'qbeta',
    'qbinom',
    'qcauchy',
    'qchisq',
    'qexp',
    'qf',
    'qgamma',
    'qgeom',
    'qhyper',
    'qlnorm',
    'qlogis',
    'qnbeta',
    'qnbinom',
    'qnbinom_mu',
    'qnchisq',
    'qnf',
    'qnorm',
    'qnt',
    'qpois',
    'qsignrank',
    'qt',
    'qtukey',
    'qunif',
    'qweibull',
    'qwilcox',
    'rbeta',
    'rbinom',
    'rcauchy',
    'rchisq',
    'rexp',
    'rf',
    'rgamma',
    'rgeom',
    'rhyper',
    'rlnorm',
    'rlogis',
    'rnbinom',
    'rnbinom_mu',
    'rnchisq',
    'rnorm',
    'rpois',
    'rsignrank',
    'rt',
    'runif',
    'rweibull',
    'rwilcox',
    'sign',
    'sinpi',
    'tanpi',
    'tetragamma',
    'trigamma',
]

# signatures (C order):
#   bessel_i(x, nu, expon_scaled)
#   bessel_j(x, nu)
#   bessel_k(x, nu, expon_scaled)
#   bessel_y(x, nu)
#   beta(a, b)
#   choose(n, k)
#   cospi(x)
#   dbeta(x, shape1, shape2, give_log)
#   dbinom(x, size, prob, give_log)
#   dbinom_raw(x, n, p, q, log_p)
#   dcauchy(x, location, scale, give_log)
#   dchisq(x, df, give_log)
#   dexp(x, rate, give_log)
#   df(x, df1, df2, give_log)
#   dgamma(x, shape, scale, give_log)
#   dgeom(x, prob, give_log)
#   dhyper(x, m, n, k, give_log)
#   digamma(x)
#   dlnorm(x, meanlog, sdlog, give_log)
#   dlogis(x, location, scale, give_log)
#   dnbeta(x, shape1, shape2, ncp, give_log)
#   dnbinom(x, size, prob, give_log)
#   dnbinom_mu(x, size, mu, give_log)
#   dnchisq(x, df, ncp, give_log)
#   dnf(x, df1, df2, ncp, give_log)
#   dnorm(x, mean, sd, give_log)
#   dnt(x, df, ncp, give_log)
#   dpois(x, lambda_, give_log)
#   dpois_raw(x, lambda, log_p)
#   dsignrank(x, n, give_log)
#   dt(x, df, give_log)
#   dunif(x, min, max, give_log)
#   dweibull(x, shape, scale, give_log)
#   dwilcox(x, m, n, give_log)
#   fprec(x, digits)
#   fround(x, digits)
#   fsign(x, y)
#   ftrunc(x)
#   gammafn(x)
#   lbeta(a, b)
#   lchoose(n, k)
#   lgamma1p(x)
#   lgammafn(x)
#   log1mexp(x)
#   log1pexp(x)
#   log1pmx(x)
#   logspace_add(logx, logy)
#   logspace_sub(logx, logy)
#   pbeta(q, shape1, shape2, lower_tail, log_p)
#   pbinom(q, size, prob, lower_tail, log_p)
#   pcauchy(q, location, scale, lower_tail, log_p)
#   pchisq(q, df, lower_tail, log_p)
#   pentagamma(x)
#   pexp(q, rate, lower_tail, log_p)
#   pf(q, df1, df2, lower_tail, log_p)
#   pgamma(q, shape, scale, lower_tail, log_p)
#   pgeom(q, prob, lower_tail, log_p)
#   phyper(q, m, n, k, lower_tail, log_p)
#   plnorm(q, meanlog, sdlog, lower_tail, log_p)
#   plogis(q, location, scale, lower_tail, log_p)
#   pnbeta(q, shape1, shape2, ncp, lower_tail, log_p)
#   pnbinom(q, size, prob, lower_tail, log_p)
#   pnbinom_mu(q, size, mu, lower_tail, log_p)
#   pnchisq(q, df, ncp, lower_tail, log_p)
#   pnf(q, df1, df2, ncp, lower_tail, log_p)
#   pnorm(q, mean, sd, lower_tail, log_p)
#   pnt(q, df, ncp, lower_tail, log_p)
#   pow1p(x, y)
#   ppois(q, lambda_, lower_tail, log_p)
#   psigamma(x, deriv)
#   psignrank(q, n, lower_tail, log_p)
#   pt(q, df, lower_tail, log_p)
#   ptukey(q, nranges, nmeans, df, lower_tail, log_p)
#   punif(q, min, max, lower_tail, log_p)
#   pweibull(q, shape, scale, lower_tail, log_p)
#   pwilcox(q, m, n, lower_tail, log_p)
#   qbeta(p, shape1, shape2, lower_tail, log_p)
#   qbinom(p, size, prob, lower_tail, log_p)
#   qcauchy(p, location, scale, lower_tail, log_p)
#   qchisq(p, df, lower_tail, log_p)
#   qexp(p, rate, lower_tail, log_p)
#   qf(p, df1, df2, lower_tail, log_p)
#   qgamma(p, shape, scale, lower_tail, log_p)
#   qgeom(p, prob, lower_tail, log_p)
#   qhyper(p, m, n, k, lower_tail, log_p)
#   qlnorm(p, meanlog, sdlog, lower_tail, log_p)
#   qlogis(p, location, scale, lower_tail, log_p)
#   qnbeta(p, shape1, shape2, ncp, lower_tail, log_p)
#   qnbinom(p, size, prob, lower_tail, log_p)
#   qnbinom_mu(p, size, mu, lower_tail, log_p)
#   qnchisq(p, df, ncp, lower_tail, log_p)
#   qnf(p, df1, df2, ncp, lower_tail, log_p)
#   qnorm(p, mean, sd, lower_tail, log_p)
#   qnt(p, df, ncp, lower_tail, log_p)
#   qpois(p, lambda_, lower_tail, log_p)
#   qsignrank(p, n, lower_tail, log_p)
#   qt(p, df, lower_tail, log_p)
#   qtukey(p, nranges, nmeans, df, lower_tail, log_p)
#   qunif(p, min, max, lower_tail, log_p)
#   qweibull(p, shape, scale, lower_tail, log_p)
#   qwilcox(p, m, n, lower_tail, log_p)
#   rbeta(shape1, shape2)
#   rbinom(size, prob)
#   rcauchy(location, scale)
#   rchisq(df)
#   rexp(rate)
#   rf(df1, df2)
#   rgamma(shape, scale)
#   rgeom(prob)
#   rhyper(m, n, k)
#   rlnorm(meanlog, sdlog)
#   rlogis(location, scale)
#   rnbinom(size, prob)
#   rnbinom_mu(size, mu)
#   rnchisq(df, ncp)
#   rnorm(mean, sd)
#   rpois(lambda_)
#   rsignrank(n)
#   rt(df)
#   runif(min, max)
#   rweibull(shape, scale)
#   rwilcox(m, n)
#   sign(x)
#   sinpi(x)
#   tanpi(x)
#   tetragamma(x)
#   trigamma(x)
