#!/usr/bin/env python3
"""Generate accudist's C ufunc, public API, stubs, raw API, and manifest test."""

from __future__ import annotations

import argparse
import difflib
import tempfile
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "docs" / "functions.toml"
GENERATED = {
    "_ufuncs.c": ROOT / "accudist" / "_ufuncs.c",
    "_api.py": ROOT / "accudist" / "_api.py",
    "_generated.pyi": ROOT / "accudist" / "_generated.pyi",
    "rmath.py": ROOT / "accudist" / "rmath.py",
    "test_manifest.py": ROOT / "tests" / "test_manifest.py",
}


def enabled_functions(data: dict) -> list[dict]:
    """M1 deliberately enables exactly one complete vertical slice."""

    return [function for function in data["func"] if function["name"] == "ppois"]


def render_c(functions: list[dict]) -> str:
    loops: list[str] = []
    registrations: list[str] = []
    for function in functions:
        name = function["name"]
        params = [param["py"] for param in function["params"]]
        flags = function["flags"]
        inputs = params + flags
        declarations: list[str] = []
        call_args: list[str] = []
        for index, item in enumerate(inputs):
            c_name = item.removesuffix("_")
            if item in flags:
                declarations.append(
                    f"        long {c_name} = *(long *)(args[{index}] + i * steps[{index}]);"
                )
                call_args.append(f"(int){c_name}")
            else:
                declarations.append(
                    f"        double {c_name} = *(double *)(args[{index}] + i * steps[{index}]);"
                )
                call_args.append(c_name)
        output_index = len(inputs)
        type_codes = ["NPY_LONG" if item in flags else "NPY_DOUBLE" for item in inputs]
        type_codes.append("NPY_DOUBLE")
        loops.append(
            f"""static void
{name}_loop(char **args, const npy_intp *dims, const npy_intp *steps, void *data)
{{
    npy_intp n = dims[0];
    (void)data;
    for (npy_intp i = 0; i < n; i++) {{
{chr(10).join(declarations)}
        *(double *)(args[{output_index}] + i * steps[{output_index}]) =
            {function['call']['c_symbol']}({', '.join(call_args)});
    }}
}}

static PyUFuncGenericFunction {name}_funcs[1] = {{{name}_loop}};
static void *{name}_data[1] = {{NULL}};
static char {name}_types[] = {{{', '.join(type_codes)}}};
"""
        )
        registrations.append(
            f"""    {{
        PyObject *ufunc = PyUFunc_FromFuncAndData(
            {name}_funcs, {name}_data, {name}_types,
            1, {len(inputs)}, 1, PyUFunc_None,
            "{name}", "Raw R nmath {name} ufunc.", 0
        );
        if (ufunc == NULL || PyModule_AddObject(module, "{name}", ufunc) < 0) {{
            Py_XDECREF(ufunc);
            Py_DECREF(module);
            return NULL;
        }}
    }}"""
        )

    return f"""/* GENERATED by tools/regen.py -- do not edit. */
#define PY_SSIZE_T_CLEAN
#define NPY_NO_DEPRECATED_API NPY_1_25_API_VERSION
#include <Python.h>
#include <numpy/arrayobject.h>
#include <numpy/ufuncobject.h>
#include <Rmath.h>
#include "accudist_shim.h"

extern void wilcox_free(void);
extern void signrank_free(void);
extern PyThread_type_lock accudist_cache_lock;
extern PyThread_type_lock accudist_rng_lock;

{chr(10).join(loops)}
static PyObject *
py_clear_error(PyObject *self, PyObject *ignored)
{{
    (void)self;
    (void)ignored;
    accudist_clear_error();
    Py_RETURN_NONE;
}}

static PyObject *
py_take_error(PyObject *self, PyObject *ignored)
{{
    (void)self;
    (void)ignored;
    return PyLong_FromUnsignedLong(accudist_take_error());
}}

static PyObject *
py_force_allocation_failure(PyObject *self, PyObject *ignored)
{{
    (void)self;
    (void)ignored;
    accudist_fatal("forced allocation failure: %d", 1);
    Py_RETURN_NONE;
}}

static PyObject *
py_free_caches(PyObject *self, PyObject *ignored)
{{
    (void)self;
    (void)ignored;
    PyThread_acquire_lock(accudist_cache_lock, WAIT_LOCK);
    wilcox_free();
    signrank_free();
    PyThread_release_lock(accudist_cache_lock);
    Py_RETURN_NONE;
}}

static PyMethodDef module_methods[] = {{
    {{"_clear_error", py_clear_error, METH_NOARGS, NULL}},
    {{"_take_error", py_take_error, METH_NOARGS, NULL}},
    {{"_force_allocation_failure", py_force_allocation_failure, METH_NOARGS, NULL}},
    {{"_free_caches", py_free_caches, METH_NOARGS, NULL}},
    {{NULL, NULL, 0, NULL}}
}};

static void
module_free(void *module)
{{
    (void)module;
    if (accudist_cache_lock != NULL) {{
        PyThread_acquire_lock(accudist_cache_lock, WAIT_LOCK);
        wilcox_free();
        signrank_free();
        PyThread_release_lock(accudist_cache_lock);
    }}
    accudist_free_locks();
}}

static struct PyModuleDef module_def = {{
    PyModuleDef_HEAD_INIT,
    "_ufuncs",
    "Generated NumPy ufuncs backed by R nmath.",
    -1,
    module_methods,
    NULL,
    NULL,
    NULL,
    module_free
}};

PyMODINIT_FUNC
PyInit__ufuncs(void)
{{
    PyObject *module;
    import_array();
    import_umath();
    if (accudist_init_locks() < 0) {{
        PyErr_NoMemory();
        return NULL;
    }}
    module = PyModule_Create(&module_def);
    if (module == NULL) {{
        accudist_free_locks();
        return NULL;
    }}
{chr(10).join(registrations)}
    return module;
}}
"""


def render_api(functions: list[dict]) -> str:
    pieces = [
        "# GENERATED by tools/regen.py -- do not edit.\n",
        "from __future__ import annotations\n\n",
        "from . import _errstate, _ufuncs\n\n",
    ]
    names: list[str] = []
    for function in functions:
        name = function["name"]
        names.append(name)
        params: list[str] = []
        arguments: list[str] = []
        for param in function["params"]:
            py_name = param["py"]
            if "default" in param:
                params.append(f"{py_name}={param['default']!r}")
            else:
                params.append(py_name)
            arguments.append(py_name)
        for flag in function["flags"]:
            default = "True" if flag == "lower_tail" else "False"
            params.append(f"{flag}={default}")
            arguments.append(f"int({flag})")
        params.append("out=None")
        pieces.append(
            f"def {name}({', '.join(params)}):\n"
            f"    \"\"\"Poisson distribution function. R: ppois(q, lambda, lower.tail, log.p).\"\"\"\n"
            f"    with _errstate.capture(\"{name}\") as _capture:\n"
            f"        result = _ufuncs.{name}({', '.join(arguments)}, out=out)\n"
            f"    _capture.check()\n"
            f"    return result\n\n"
        )
    pieces.append(f"__all__ = {names!r}\n")
    return "".join(pieces)


def render_stub(functions: list[dict]) -> str:
    lines = [
        "# GENERATED by tools/regen.py -- do not edit.\n",
        "from typing import Any\n",
        "import numpy as np\n\n",
    ]
    for function in functions:
        params: list[str] = []
        for param in function["params"]:
            default = f" = {param['default']!r}" if "default" in param else ""
            params.append(f"{param['py']}: Any{default}")
        for flag in function["flags"]:
            default = "True" if flag == "lower_tail" else "False"
            params.append(f"{flag}: bool = {default}")
        params.append("out: Any = None")
        lines.append(f"def {function['name']}({', '.join(params)}) -> np.float64 | np.ndarray[Any, Any]: ...\n")
    return "".join(lines)


def render_rmath(functions: list[dict]) -> str:
    names = [function["name"] for function in functions]
    lines = [
        "# GENERATED by tools/regen.py -- do not edit.\n",
        '"""Raw, positional, one-to-one mappings to Rmath.h."""\n',
        "from . import _ufuncs\n\n",
    ]
    lines.extend(f"{name} = _ufuncs.{name}\n" for name in names)
    lines.append(f"\n__all__ = {names!r}\n")
    return "".join(lines)


def render_manifest_test(functions: list[dict]) -> str:
    names = [function["name"] for function in functions]
    return f'''# GENERATED by tools/regen.py -- do not edit.
import pytest
import accudist as ad


@pytest.mark.parametrize("name", {names!r})
def test_manifest_function_is_public(name):
    assert callable(getattr(ad, name))
    assert name in ad.__all__
'''


def render_all(manifest: Path) -> dict[str, str]:
    data = tomllib.loads(manifest.read_text())
    functions = enabled_functions(data)
    return {
        "_ufuncs.c": render_c(functions),
        "_api.py": render_api(functions),
        "_generated.pyi": render_stub(functions),
        "rmath.py": render_rmath(functions),
        "test_manifest.py": render_manifest_test(functions),
    }


def write_outputs(outputs: dict[str, str], output_dir: Path, build_mode: bool) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for name, content in outputs.items():
        target = output_dir / name
        if not build_mode and name == "test_manifest.py":
            target = ROOT / "tests" / name
        target.write_text(content)


def check_outputs(outputs: dict[str, str]) -> int:
    failed = False
    for name, content in outputs.items():
        target = GENERATED[name]
        actual = target.read_text() if target.exists() else ""
        if actual == content:
            continue
        failed = True
        print(f"stale generated file: {target.relative_to(ROOT)}")
        print("".join(difflib.unified_diff(actual.splitlines(True), content.splitlines(True))))
    return int(failed)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", nargs="?", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("output_dir", nargs="?", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = render_all(args.manifest)
    if args.check:
        raise SystemExit(check_outputs(outputs))
    output_dir = args.output_dir or ROOT / "accudist"
    write_outputs(outputs, output_dir, build_mode=args.output_dir is not None)


if __name__ == "__main__":
    main()
