#!/usr/bin/env python3
"""Generate accudist's C ufunc table and Python API from functions.toml.

Outputs (all committed; `--check` verifies none is stale):

    src/_ufuncs_generated.c     one NumPy ufunc per Rmath.h symbol
    accudist/_api.py            public wrappers: defaults, kwargs, dispatch, docs
    accudist/rmath.py           raw 1:1 escape hatch
    docs/api-reference.md       function tables for the documentation site

Every C call is validated against the prototypes in vendor/nmath/include/Rmath.h,
so a wrong `c_args` list fails here rather than returning plausible numbers.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10
    import tomli as tomllib  # type: ignore[no-redef]

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "functions.toml"
RMATH_H = ROOT / "vendor" / "nmath" / "include" / "Rmath.h"
OUTPUTS = {
    "c": ROOT / "src" / "_ufuncs_generated.c",
    "api": ROOT / "accudist" / "_api.py",
    "rmath": ROOT / "accudist" / "rmath.py",
    "docs": ROOT / "docs" / "api-reference.md",
}

HEADER_C = "/* GENERATED by tools/regen.py from functions.toml -- do not edit. */\n"
HEADER_PY = "# GENERATED by tools/regen.py from functions.toml -- do not edit.\n"
HEADER_MD = "<!-- GENERATED by tools/regen.py from functions.toml -- do not edit. -->\n"

# Raw-only symbols: no public wrapper, but reachable through accudist.rmath.
RAW_ONLY = {
    "dbinom_raw": (["x", "n", "p", "q"], ["give_log"]),
    "dpois_raw": (["x", "lambda"], ["give_log"]),
}

# --------------------------------------------------------------------------
# documentation metadata
# --------------------------------------------------------------------------

FAMILY_TITLE = {
    "norm": "normal", "unif": "uniform", "gamma": "gamma", "beta": "beta",
    "lnorm": "log-normal", "chisq": "chi-squared", "f": "F", "t": "Student t",
    "binom": "binomial", "cauchy": "Cauchy", "exp": "exponential", "geom": "geometric",
    "hyper": "hypergeometric", "nbinom": "negative binomial", "pois": "Poisson",
    "weibull": "Weibull", "logis": "logistic", "wilcox": "Wilcoxon rank sum",
    "signrank": "Wilcoxon signed rank", "tukey": "studentized range (Tukey)",
}

PARAM_DOC = {
    ("*", "x"): "Value(s) at which to evaluate the density or mass function.",
    ("*", "q"): "Quantile(s).",
    ("*", "p"): "Probability(ies); on the log scale when ``log=True``.",
    ("*", "ncp"): (
        "Non-centrality parameter. ``None`` (the default) selects R's central "
        "algorithm; any value, including ``0.0``, selects the non-central one, exactly "
        "as R dispatches on ``missing(ncp)``."
    ),
    ("*", "lower_tail"): "If ``False``, return the upper tail ``P[X > q]`` computed directly (not ``1 - cdf``).",
    ("*", "log"): "If ``True``, probabilities are on the natural-log scale.",
    ("norm", "mean"): "Mean.", ("norm", "sd"): "Standard deviation.",
    ("unif", "min"): "Lower limit.", ("unif", "max"): "Upper limit.",
    ("gamma", "shape"): "Shape parameter (positive).",
    ("gamma", "rate"): "Rate parameter, ``1/scale``. Used when ``scale`` is not given; defaults to 1.",
    ("gamma", "scale"): "Scale parameter. Specify either ``rate`` or ``scale``, not both.",
    ("beta", "shape1"): "First positive shape parameter.", ("beta", "shape2"): "Second positive shape parameter.",
    ("lnorm", "meanlog"): "Mean of the distribution on the log scale.",
    ("lnorm", "sdlog"): "Standard deviation on the log scale.",
    ("chisq", "df"): "Degrees of freedom (non-negative, need not be an integer).",
    ("f", "df1"): "Numerator degrees of freedom.", ("f", "df2"): "Denominator degrees of freedom.",
    ("t", "df"): "Degrees of freedom (positive, may be non-integer).",
    ("binom", "size"): "Number of trials (zero or more).", ("binom", "prob"): "Probability of success on each trial.",
    ("cauchy", "location"): "Location parameter.", ("cauchy", "scale"): "Scale parameter.",
    ("exp", "rate"): "Rate, ``1/mean``. The C library takes a scale; accudist passes ``1/rate`` as R does.",
    ("geom", "prob"): "Probability of success in each trial. Support starts at 0 (number of failures).",
    ("hyper", "m"): "Number of white balls in the urn.", ("hyper", "n"): "Number of black balls in the urn.",
    ("hyper", "k"): "Number of balls drawn from the urn.",
    ("nbinom", "size"): "Target number of successful trials (dispersion parameter); need not be an integer.",
    ("nbinom", "prob"): "Probability of success in each trial. Specify either ``prob`` or ``mu``.",
    ("nbinom", "mu"): "Alternative parametrisation by the mean. Specify either ``prob`` or ``mu``.",
    ("pois", "lambda_"): "Mean (R's ``lambda``; renamed because ``lambda`` is a Python keyword).",
    ("weibull", "shape"): "Shape parameter.", ("weibull", "scale"): "Scale parameter.",
    ("logis", "location"): "Location parameter.", ("logis", "scale"): "Scale parameter.",
    ("wilcox", "m"): "Number of observations in the first sample.",
    ("wilcox", "n"): "Number of observations in the second sample.",
    ("signrank", "n"): "Number of observations in the sample.",
    ("tukey", "nmeans"): "Sample size for the range (number of groups).",
    ("tukey", "df"): "Degrees of freedom for the standard-error estimate.",
    ("tukey", "nranges"): "Number of groups whose maximum range is considered.",
    ("special", "x"): "Argument.", ("special", "a"): "First argument.", ("special", "b"): "Second argument.",
    ("special", "n"): "``n`` in ``choose(n, k)``; need not be an integer.",
    ("special", "k"): "``k`` in ``choose(n, k)``; rounded to an integer, with a warning if it was not one.",
    ("special", "nu"): "Order of the Bessel function.",
    ("special", "deriv"): "Order of the derivative (0 gives ``digamma``).",
    ("special", "expon_scaled"): "If ``True``, return the exponentially scaled function (R's ``expon.scaled``).",
    ("util", "x"): "Argument.", ("util", "y"): "Argument whose sign is used.",
    ("util", "digits"): "Number of digits.", ("util", "logx"): "``log(x)``.", ("util", "logy"): "``log(y)``.",
}

KIND_TITLE = {"d": "density (mass) function", "p": "distribution function", "q": "quantile function", "r": "random generation"}

R_ARG_NAME = {"lambda_": "lambda", "expon_scaled": "expon.scaled"}

RNG_CAVEAT = (
    "Draws come from standalone Rmath's Marsaglia-MultiCarry generator, so they do\n"
    "    **not** reproduce R's default (Mersenne-Twister) ``set.seed()`` streams. They do\n"
    "    reproduce R exactly when R is switched to the same generator:\n"
    "    ``RNGkind(\"Marsaglia-Multicarry\", \"Inversion\", \"Rejection\"); set.seed(s)`` in R\n"
    "    pairs with ``accudist.set_r_seed(s)`` / ``RNG.from_r_seed(s)`` here."
)

# Python code for the R-level compositions of non-central draws (functions.toml
# records the R expression; this is its accudist translation).
COMPOSED = {
    "rbeta": (
        "    X = _rchisq(rng, n, 2.0 * _np.asarray(shape1, dtype=float), ncp=ncp)\n"
        "    return X / (X + _rchisq(rng, n, 2.0 * _np.asarray(shape2, dtype=float)))\n"
    ),
    "rf": (
        "    df1 = _recycle(df1, n, 'df1')\n"
        "    df2 = _recycle(df2, n, 'df2')\n"
        "    return (_rchisq(rng, n, df1, ncp=ncp) / df1) / (_rchisq(rng, n, df2) / df2)\n"
    ),
    "rt": (
        "    df = _recycle(df, n, 'df')\n"
        "    return _rnorm(rng, n, ncp, 1.0) / _np.sqrt(_rchisq(rng, n, df) / df)\n"
    ),
}

# --------------------------------------------------------------------------
# manifest helpers
# --------------------------------------------------------------------------


def load_manifest() -> dict:
    return tomllib.loads(MANIFEST.read_text())


def calls(func: dict):
    for key in ("call", "call_ncp", "call_mu"):
        c = func.get(key)
        if c and "c_symbol" in c:
            yield key, c


def value_inputs(func: dict, call: dict) -> list[str]:
    """C double arguments (public names) for one call, in C order."""
    if func["kind"] in ("d", "p", "q"):
        return [func["params"][0]["py"], *call["c_args"]]
    return list(call["c_args"])


def ufunc_table(manifest: dict) -> dict[str, tuple[list[str], list[str]]]:
    """c_symbol -> (double input names, flag names)."""
    table: dict[str, tuple[list[str], list[str]]] = {}
    for f in manifest["func"]:
        for _, c in calls(f):
            sig = (value_inputs(f, c), list(f["flags"]))
            prev = table.get(c["c_symbol"])
            if prev is not None and prev != sig:
                raise SystemExit(f"inconsistent signatures for C symbol {c['c_symbol']}: {prev} vs {sig}")
            table[c["c_symbol"]] = sig
    for sym, sig in RAW_ONLY.items():
        table[sym] = sig
    return table


def rmath_prototypes() -> dict[str, tuple[int, int]]:
    """symbol -> (number of double args, number of int args) from Rmath.h."""
    protos: dict[str, tuple[int, int]] = {}
    pat = re.compile(r"^\s*double\s+(\w+)\s*\(([^)]*)\)\s*;", re.M)
    for m in pat.finditer(RMATH_H.read_text()):
        args = [a.strip() for a in m.group(2).split(",") if a.strip()]
        if any("*" in a for a in args):
            continue
        protos[m.group(1)] = (sum(a.startswith("double") for a in args), sum(a.startswith("int") for a in args))
    return protos


def validate(table: dict) -> None:
    protos = rmath_prototypes()
    for sym, (vals, flags) in table.items():
        if sym not in protos:
            raise SystemExit(f"{sym}: no scalar prototype in Rmath.h")
        nd, ni = protos[sym]
        if (nd, ni) != (len(vals), len(flags)):
            raise SystemExit(f"{sym}: Rmath.h has ({nd} double, {ni} int) but manifest gives {vals} + {flags}")


def flag_c_name(kind: str, flag: str) -> str:
    if flag == "lower_tail":
        return "lower_tail"
    return "give_log" if kind == "d" else "log_p"


# --------------------------------------------------------------------------
# C generation
# --------------------------------------------------------------------------


def render_c(manifest: dict, table: dict) -> str:
    kind_of = {c["c_symbol"]: f["kind"] for f in manifest["func"] for _, c in calls(f)}
    out = [HEADER_C, '''
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#define NPY_NO_DEPRECATED_API NPY_1_25_API_VERSION
/* share the NumPy C-API tables imported by _ufuncsmodule.c */
#define PY_ARRAY_UNIQUE_SYMBOL accudist_ARRAY_API
#define PY_UFUNC_UNIQUE_SYMBOL accudist_UFUNC_API
#define NO_IMPORT_ARRAY
#define NO_IMPORT_UFUNC
#include <numpy/arrayobject.h>
#include <numpy/ufuncobject.h>
#include <fenv.h>
#include <math.h>
#include <Rmath.h>

#define D(p) (*(double *)(p))
#define FLAG(p) ((int)(*(double *)(p) != 0.0))

static void *no_data[1] = {NULL};
''']
    regs = []
    for sym, (vals, flags) in table.items():
        nin = len(vals) + len(flags)
        ptrs = ", ".join(f"*a{i} = args[{i}]" for i in range(nin))
        call_args = ", ".join([f"D(a{i})" for i in range(len(vals))] + [f"FLAG(a{len(vals) + j})" for j in range(len(flags))])
        steps = " ".join(f"a{i} += steps[{i}];" for i in range(nin))
        kind = kind_of.get(sym, "special")
        if kind == "r":
            body = f"D(o) = {sym}({call_args});"
        else:
            # R's own wrappers (arithmetic.c math1..math4) return NaN when any
            # argument is NaN *before* calling nmath; a few nmath entry points
            # (pnt, ...) would otherwise return a finite value. Mirror that.
            nan_test = " || ".join(f"isnan(D(a{i}))" for i in range(len(vals)))
            nan_val = " + ".join(f"D(a{i})" for i in range(len(vals)))
            body = f"D(o) = ({nan_test}) ? ({nan_val}) : {sym}({call_args});"
        out.append(f'''
static void {sym}_loop(char **args, npy_intp const *dims, npy_intp const *steps, void *data)
{{
    npy_intp n = dims[0];
    char {ptrs}, *o = args[{nin}];
    for (npy_intp i = 0; i < n; i++) {{
        {body}
        {steps} o += steps[{nin}];
    }}
    /* nmath computes with Inf/NaN deliberately (R never warns about FP flags);
       discard the status so NumPy does not raise spurious RuntimeWarnings. */
    feclearexcept(FE_ALL_EXCEPT);
}}
static PyUFuncGenericFunction {sym}_funcs[1] = {{&{sym}_loop}};
static char {sym}_types[{nin + 1}] = {{{", ".join(["NPY_DOUBLE"] * (nin + 1))}}};
''')
        doc_args = ", ".join(vals + [flag_c_name(kind, fl) for fl in flags])
        regs.append(
            f'    ADD("{sym}", {sym}_funcs, {sym}_types, {nin}, "{sym}({doc_args}) -> double  [C: {sym}]");'
        )
    out.append('''
#define ADD(name, funcs, types, nin, doc)                                          \\
    do {                                                                            \\
        PyObject *f = PyUFunc_FromFuncAndData(funcs, no_data, types, 1, nin, 1,     \\
                                              PyUFunc_None, name, doc, 0);          \\
        if (f == NULL || PyModule_AddObject(m, name, f) < 0) {                      \\
            Py_XDECREF(f);                                                          \\
            return -1;                                                              \\
        }                                                                           \\
    } while (0)

int accudist_add_generated_ufuncs(PyObject *m)
{
''')
    out.extend(r + "\n" for r in regs)
    out.append("    return 0;\n}\n")
    return "".join(out)


# --------------------------------------------------------------------------
# Python API generation
# --------------------------------------------------------------------------


def r_signature(f: dict) -> str:
    """R's own call signature for the docstring."""
    kind = f["kind"]
    parts = []
    for p in f["params"]:
        name = R_ARG_NAME.get(p["py"], p["py"])
        if f.get("alias") == "rate_scale" and name == "scale":
            parts.append("scale = 1/rate")
        elif "default" in p:
            d = p["default"]
            parts.append(f"{name} = {'TRUE' if d is True else 'FALSE' if d is False else int(d) if float(d).is_integer() else d}")
        else:
            parts.append(name)
    if f.get("dispatch") == "ncp":
        parts.append("ncp")
    if kind == "d":
        parts.append("log = FALSE")
    elif kind in ("p", "q"):
        parts += ["lower.tail = TRUE", "log.p = FALSE"]
    r_name = f.get("r_equivalent", "").split("(")[0] or f["name"]
    if kind in "dpqr":
        r_name = f["name"]
    return f"{r_name}({', '.join(parts)})"


def py_default(p: dict) -> str:
    if "default" not in p:
        return ""
    d = p["default"]
    if isinstance(d, bool):
        return f"={d}"
    return f"={d!r}"


def public_params(f: dict) -> list[str]:
    """Python parameter list (without flags / out)."""
    kind = f["kind"]
    ps = []
    for i, p in enumerate(f["params"]):
        name = p["py"]
        if f.get("alias") == "rate_scale" and name in ("rate", "scale"):
            ps.append(f"{name}=None")
        elif f.get("dispatch") == "prob_or_mu" and name in ("prob", "mu"):
            ps.append(f"{name}=None")
        else:
            ps.append(name + py_default(p))
    if f.get("dispatch") == "ncp":
        ps.append("ncp=None")
    if kind == "d":
        ps.append("log=False")
    elif kind in ("p", "q"):
        ps += ["lower_tail=True", "log=False"]
    return ps


def param_doc(f: dict, name: str) -> str:
    fam = f.get("family") or f["kind"]
    for key in ((fam, name), ("*", name), (f["kind"], name)):
        if key in PARAM_DOC:
            return PARAM_DOC[key]
    return ""


def docstring(f: dict) -> str:
    kind, name = f["kind"], f["name"]
    fam = f.get("family")
    if kind in "dpqr":
        ft = FAMILY_TITLE[fam]
        title = f"{ft[0].upper() + ft[1:]} {KIND_TITLE[kind]}."
    else:
        title = (f.get("summary") or f"``{f.get('r_equivalent', name)}`` from R.").rstrip(".") + "."
        title = title[0].upper() + title[1:]
    lines = [title, ""]
    lines.append(f"R equivalent: ``{r_signature(f)}``")
    if fam and f.get("r_page"):
        lines.append(f"(help page ``?{f['r_page']}``).")
    if f.get("note"):
        lines.append(f"Note: {f['note']}.")
    lines += ["", "Parameters", "----------"]
    if kind == "r":
        lines += [f"{f['params'][0]['py']} : int", "    Number of draws. Other parameters recycle to this length as in R."]
        params = f["params"][1:]
    else:
        params = f["params"]
    for p in params:
        pname = p["py"]
        lines.append(f"{pname} : array_like" + (", optional" if ("default" in p or pname in ("scale", "mu", "prob") and (f.get("alias") or f.get("dispatch"))) else ""))
        doc = param_doc(f, pname)
        if doc:
            lines.append(f"    {doc}")
    if f.get("dispatch") == "ncp":
        lines += ["ncp : array_like, optional", f"    {PARAM_DOC[('*', 'ncp')]}"]
    if kind in "dpq":
        if kind in "pq":
            lines += ["lower_tail : bool, default True", f"    {PARAM_DOC[('*', 'lower_tail')]}"]
        lines += ["log : bool, default False", f"    {PARAM_DOC[('*', 'log')]}"]
    if kind != "r":
        lines += ["out : ndarray, optional", "    Preallocated output array (passed to the underlying ufunc)."]
    lines += ["", "Returns", "-------"]
    if kind == "r":
        lines += ["ndarray", f"    ``float64`` array of length ``{f['params'][0]['py']}``, even for discrete distributions."]
        lines += ["", "Notes", "-----", f"{RNG_CAVEAT}"]
    else:
        lines += ["numpy.float64 or ndarray", "    Scalar inputs give a NumPy scalar; array inputs broadcast."]
        if kind == "q":
            lines += ["    Quantiles of discrete distributions are returned as doubles, as R does."]
    if f.get("cache"):
        lines += ["", "Notes", "-----",
                  "Uses a process-wide distribution table guarded by a lock; concurrent calls",
                  "serialise. Memory grows with the sample sizes; ``accudist.free_caches()`` releases it."]
    return "\n".join(lines)


def indent(text: str, n: int = 4) -> str:
    pad = " " * n
    return "\n".join(pad + ln if ln else "" for ln in text.splitlines())


def ufunc_call(f: dict, call: dict, var_map: dict[str, str], flags_expr: list[str], out: bool) -> str:
    args = [var_map.get(a, a) for a in value_inputs(f, call)] + flags_expr
    tail = ", out=out" if out else ""
    return f"_uf.{call['c_symbol']}({', '.join(args)}{tail})"


def render_dpq(f: dict) -> str:
    kind, name = f["kind"], f["name"]
    params = ", ".join(public_params(f))
    flags = ["lower_tail", "log"] if kind in "pq" else ["log"]
    body = []
    var_map: dict[str, str] = {}
    if f.get("c_transform"):
        for k, expr in f["c_transform"].items():
            if expr == "1.0 / rate":
                body.append(f"    {k} = _inv({k})")
            else:
                body.append(f"    {k} = {expr}")
    if f.get("alias") == "rate_scale":
        body.append(f"    scale = _resolve_rate_scale(rate, scale, {name!r})")
    lock = "_cache_lock" if f.get("cache") else None
    ind = "    "
    body.append(f"{ind}_clear()")
    if lock:
        body.append(f"{ind}with {lock}:")
        ind += "    "
    if f.get("dispatch") == "ncp":
        body.append(f"{ind}if ncp is None:")
        body.append(f"{ind}    r = {ufunc_call(f, f['call'], var_map, flags, True)}")
        body.append(f"{ind}else:")
        body.append(f"{ind}    r = {ufunc_call(f, f['call_ncp'], var_map, flags, True)}")
    elif f.get("dispatch") == "prob_or_mu":
        body.append(f"{ind}if _resolve_prob_mu(prob, mu, {name!r}):")
        body.append(f"{ind}    r = {ufunc_call(f, f['call_mu'], var_map, flags, True)}")
        body.append(f"{ind}else:")
        body.append(f"{ind}    r = {ufunc_call(f, f['call'], var_map, flags, True)}")
    else:
        body.append(f"{ind}r = {ufunc_call(f, f['call'], var_map, flags, True)}")
    body.append(f"    _check({name!r})")
    body.append("    return r")
    return (
        f"\n\ndef {name}({params}, *, out=None):\n"
        f'    """\n{indent(docstring(f))}\n    """\n' + "\n".join(body) + "\n"
    )


def render_special(f: dict) -> str:
    name = f["name"]
    params = ", ".join(public_params(f))
    body = []
    for k, expr in (f.get("c_transform") or {}).items():
        body.append(f"    {k} = {expr}")
    body.append("    _clear()")
    body.append(f"    r = {ufunc_call(f, f['call'], {}, [], True)}")
    body.append(f"    _check({name!r})")
    body.append("    return r")
    return (
        f"\n\ndef {name}({params}, *, out=None):\n"
        f'    """\n{indent(docstring(f))}\n    """\n' + "\n".join(body) + "\n"
    )


def render_r(f: dict) -> tuple[str, str, str]:
    """Returns (impl function, module-level function, RNG method)."""
    name = f["name"]
    count = f["params"][0]["py"]
    params = public_params(f)
    sig = ", ".join(params)
    arg_names = [p.split("=")[0] for p in params]
    fwd = ", ".join(arg_names)
    body = [f"    {count} = _draw_count({count})"]
    var_map: dict[str, str] = {}
    for k, expr in (f.get("c_transform") or {}).items():
        body.append(f"    {k} = _inv({k})" if expr == "1.0 / rate" else f"    {k} = {expr}")
    if f.get("alias") == "rate_scale":
        body.append(f"    scale = _resolve_rate_scale(rate, scale, {name!r})")

    def rec(call: dict) -> str:
        args = ", ".join(f"_recycle({a}, {count}, {a!r})" for a in call["c_args"])
        return f"rng._draw({name!r}, _uf.{call['c_symbol']}, ({args},))"

    if f.get("dispatch") == "ncp":
        body.append("    if ncp is None:")
        body.append(f"        return {rec(f['call'])}")
        if "c_symbol" in f["call_ncp"]:
            body.append(f"    return {rec(f['call_ncp'])}")
        else:
            body.append("    with _rng_lock:  # composed draw is atomic w.r.t. other threads")
            body.append(indent(COMPOSED[name].rstrip("\n"), 4))
    elif f.get("dispatch") == "prob_or_mu":
        body.append(f"    if _resolve_prob_mu(prob, mu, {name!r}):")
        body.append(f"        return {rec(f['call_mu'])}")
        body.append(f"    return {rec(f['call'])}")
    else:
        body.append(f"    return {rec(f['call'])}")
    impl = f"\n\ndef _{name}(rng, {sig}):\n" + "\n".join(body) + "\n"
    doc = f'    """\n{indent(docstring(f))}\n    """\n'
    public = f"\n\ndef {name}({sig}):\n{doc}    return _{name}(_default_rng, {fwd})\n"
    method = (
        f"\n    def {name}(self, {sig}):\n"
        f'        """{KIND_TITLE["r"].capitalize()} for the {FAMILY_TITLE[f["family"]]} distribution on this stream; see :func:`accudist.{name}`."""\n'
        f"        return _{name}(self, {fwd})\n"
    )
    return impl, public, method


def render_api(manifest: dict) -> str:
    funcs = manifest["func"]
    out = [HEADER_PY, '''"""Public R-style distribution functions (generated).

Thin wrappers over :mod:`accudist._ufuncs`: resolve defaults and keyword names,
select the C symbol (``ncp``, ``prob``/``mu``, ``rate``/``scale``), call one ufunc,
then translate the thread-local nmath error word into warnings or exceptions.
"""

from __future__ import annotations

import numpy as _np

from . import _ufuncs as _uf
from ._core import (
    RNGBase as _RNGBase,
    _cache_lock,
    _draw_count,
    _inv,
    _recycle,
    _resolve_prob_mu,
    _resolve_rate_scale,
    _rng_lock,
)
from ._errstate import _check, _clear

__all__ = [
''']
    names = [f["name"] for f in funcs] + ["RNG"]
    out.extend(f"    {n!r},\n" for n in names)
    out.append("]\n")
    impls, publics, methods = [], [], []
    for f in funcs:
        if f["kind"] in "dpq":
            out.append(render_dpq(f))
        elif f["kind"] == "r":
            i, p, m = render_r(f)
            impls.append(i)
            publics.append(p)
            methods.append(m)
        else:
            out.append(render_special(f))
    out.append("\n\n# --- random generation ---------------------------------------------------\n")
    out.extend(impls)
    out.append('''

class RNG(_RNGBase):
    """An independent random-number stream with one method per ``r*`` function.

    ``RNG(i1, i2)`` holds the two 32-bit words of Rmath's Marsaglia-MultiCarry
    state. Each draw installs this state into the C library under a process-wide
    lock, runs the whole vectorised draw, and saves the state back, so streams are
    independent and thread-safe.

    Draws do **not** reproduce R's ``set.seed()`` (R uses Mersenne-Twister); only
    the sampling algorithms are R's.
    """

    __slots__ = ()
''')
    out.extend(methods)
    out.append("\n\n_default_rng = RNG()\n")
    out.extend(publics)
    return "".join(out)


def render_rmath(table: dict, manifest: dict) -> str:
    kind_of = {c["c_symbol"]: f["kind"] for f in manifest["func"] for _, c in calls(f)}
    lines = [HEADER_PY, '''"""Raw 1:1 access to the vendored ``Rmath.h`` symbols.

Every function here is the NumPy ufunc that wraps the C symbol of the same name:
positional arguments in **C order**, ``lower_tail``/``log_p`` flags as trailing
0/1 inputs, no defaults, no ``ncp``/``mu``/``scale`` dispatch, and no error
translation (the thread-local nmath error word is left untouched). Prefer the
public :mod:`accudist` API; use this when you need e.g. ``pnchisq`` or
``dbinom_raw`` directly.

Note that ``r*`` functions here draw from the global generator without taking
the RNG lock; use :class:`accudist.RNG` for thread-safe draws.
"""

from ._ufuncs import (
''']
    for sym in sorted(table):
        lines.append(f"    {sym},\n")
    lines.append(")\n\n__all__ = [\n")
    for sym in sorted(table):
        lines.append(f"    {sym!r},\n")
    lines.append("]\n\n# signatures (C order):\n")
    for sym in sorted(table):
        vals, flags = table[sym]
        kind = kind_of.get(sym, "special")
        lines.append(f"#   {sym}({', '.join(vals + [flag_c_name(kind, fl) for fl in flags])})\n")
    return "".join(lines)


def render_docs(manifest: dict) -> str:
    funcs = manifest["func"]
    out = [HEADER_MD, "# API reference\n\n",
           "All functions accept scalars or array-likes and broadcast like NumPy ufuncs. ",
           "`lower_tail=False` selects R's direct upper-tail algorithm; `log=True` works on the log scale for `d`, `p` and `q` alike.\n\n",
           "## Distributions\n\n| accudist | R | notes |\n|---|---|---|\n"]
    for f in funcs:
        if f["kind"] not in "dpqr":
            continue
        notes = []
        if f.get("dispatch") == "ncp":
            notes.append("`ncp=None` -> central algorithm; any value -> non-central")
        if f.get("dispatch") == "prob_or_mu":
            notes.append("exactly one of `prob`, `mu`")
        if f.get("alias") == "rate_scale":
            notes.append("`rate` or `scale`, not both")
        if f.get("c_transform", {}).get("rate"):
            notes.append("C takes `scale = 1/rate`")
        if f["name"] in ("ptukey", "qtukey"):
            notes.append("C argument order differs from R's; handled internally")
        if f.get("cache"):
            notes.append("locked shared table; see `free_caches()`")
        if f["kind"] == "r":
            notes.append("not R's `set.seed()` stream")
        sig = f"`{f['name']}({', '.join(public_params(f))}{'' if f['kind'] == 'r' else ', *, out=None'})`"
        out.append(f"| {sig} | `{r_signature(f)}` | {'; '.join(notes)} |\n")
    out.append("\n## Special functions\n\nThese keep Rmath's C names, so `gammafn` sits unambiguously beside `dgamma`.\n\n| accudist | R | summary |\n|---|---|---|\n")
    for f in funcs:
        if f["kind"] == "special":
            out.append(f"| `{f['name']}({', '.join(public_params(f))})` | `{f.get('r_equivalent', '')}` | {f.get('summary', f.get('note', ''))} |\n")
    out.append("\n## Numerical utilities\n\n| accudist | summary |\n|---|---|\n")
    for f in funcs:
        if f["kind"] == "util":
            out.append(f"| `{f['name']}({', '.join(public_params(f))})` | {f.get('summary', '')} |\n")
    out.append("\n## Bespoke wrappers\n\n| accudist | C symbol | why not a plain ufunc |\n|---|---|---|\n")
    for b in manifest["bespoke"]:
        out.append(f"| `{b['name']}` | `{b['c_symbol']}` | {b['reason']} |\n")
    out.append("\n## RNG primitives\n\n| accudist | summary |\n|---|---|\n")
    for r in manifest["rng_primitive"]:
        out.append(f"| `{r['name']}` | {r['summary']} |\n")
    out.append("\n## Deliberately excluded `Rmath.h` symbols\n\n| symbol | reason |\n|---|---|\n")
    for e in manifest["excluded"]:
        out.append(f"| `{e['c_symbol']}` | {e['reason']} |\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if any generated file is stale")
    args = ap.parse_args()

    manifest = load_manifest()
    table = ufunc_table(manifest)
    validate(table)
    rendered = {
        "c": render_c(manifest, table),
        "api": render_api(manifest),
        "rmath": render_rmath(table, manifest),
        "docs": render_docs(manifest),
    }
    stale = []
    for key, text in rendered.items():
        path = OUTPUTS[key]
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("stale generated files (run tools/regen.py):\n  " + "\n  ".join(stale), file=sys.stderr)
        return 1
    print(f"{len(table)} ufuncs, {len(manifest['func'])} public functions" + (" -- up to date" if args.check else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
