#!/usr/bin/env python3
"""Generate accudist's C ufunc, public API, stubs, raw API, and manifest test."""

from __future__ import annotations

import argparse
import difflib
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "docs" / "functions.toml"
GENERATED = {
    "_ufuncs.c": ROOT / "accudist" / "_ufuncs.c",
    "_api.py": ROOT / "accudist" / "_api.py",
    "_generated.pyi": ROOT / "accudist" / "_generated.pyi",
    "rmath.py": ROOT / "accudist" / "rmath.py",
    "test_manifest.py": ROOT / "tests" / "test_manifest.py",
}


def enabled_functions(data: dict) -> list[dict]:
    """M2 enables the whole central table after the M1 gate is green."""

    return [function for function in data["func"] if function["milestone"] in {"M2", "M3"}]


def call_entries(function: dict):
    for key in ("call", "call_ncp", "call_mu"):
        call = function.get(key)
        if call and "c_symbol" in call:
            yield key, call


def call_inputs(function: dict, call: dict) -> list[str]:
    if function["kind"] in {"d", "p", "q"}:
        values = [function["params"][0]["py"], *call["c_args"]]
    else:
        values = list(call["c_args"])
    return [*values, *function["flags"]]


def ufunc_specs(functions: list[dict]) -> dict[str, dict]:
    specs: dict[str, dict] = {}
    for function in functions:
        for _, call in call_entries(function):
            symbol = call["c_symbol"]
            inputs = call_inputs(function, call)
            flags = set(function["flags"])
            spec = {
                "symbol": symbol,
                "inputs": inputs,
                "flags": flags,
                "cache": function.get("cache"),
            }
            previous = specs.get(symbol)
            if previous and (
                previous["inputs"] != inputs
                or previous["flags"] != flags
                or previous["cache"] != spec["cache"]
            ):
                raise ValueError(f"inconsistent signatures for C symbol {symbol}")
            specs[symbol] = spec
    return specs


def c_identifier(name: str) -> str:
    result = name.removesuffix("_")
    if result in {"log", "sign"}:
        result += "_arg"
    return result


def render_c(functions: list[dict]) -> str:
    loops: list[str] = []
    registrations: list[str] = []
    for symbol, spec in ufunc_specs(functions).items():
        inputs = spec["inputs"]
        flags = spec["flags"]
        declarations: list[str] = []
        call_args: list[str] = []
        for index, item in enumerate(inputs):
            name = c_identifier(item)
            if item in flags:
                declarations.append(
                    f"        long {name} = *(long *)(args[{index}] + i * steps[{index}]);"
                )
                call_args.append(f"(int){name}")
            else:
                declarations.append(
                    f"        double {name} = *(double *)(args[{index}] + i * steps[{index}]);"
                )
                call_args.append(name)
        output_index = len(inputs)
        lock_before = ""
        lock_after = ""
        if spec["cache"]:
            lock_before = "    PyThread_acquire_lock(accudist_cache_lock, WAIT_LOCK);\n"
            lock_after = "    PyThread_release_lock(accudist_cache_lock);\n"
        type_codes = ["NPY_LONG" if item in flags else "NPY_DOUBLE" for item in inputs]
        type_codes.append("NPY_DOUBLE")
        call = f"{symbol}({', '.join(call_args)})"
        loops.append(
            f"""static void
{symbol}_loop(char **args, const npy_intp *dims, const npy_intp *steps, void *data)
{{
    npy_intp n = dims[0];
    (void)data;
{lock_before}    
    for (npy_intp i = 0; i < n; i++) {{
{chr(10).join(declarations)}
        jmp_buf jump;
        accudist_jump_target = &jump;
        if (setjmp(jump) == 0) {{
            *(double *)(args[{output_index}] + i * steps[{output_index}]) = {call};
        }} else {{
            *(double *)(args[{output_index}] + i * steps[{output_index}]) = NPY_NAN;
        }}
        accudist_jump_target = NULL;
    }}
{lock_after}}}

static PyUFuncGenericFunction {symbol}_funcs[1] = {{{symbol}_loop}};
static void *{symbol}_data[1] = {{NULL}};
static char {symbol}_types[] = {{{', '.join(type_codes)}}};
"""
        )
        registrations.append(
            f"""    {{
        PyObject *ufunc = PyUFunc_FromFuncAndData(
            {symbol}_funcs, {symbol}_data, {symbol}_types,
            1, {len(inputs)}, 1, PyUFunc_None,
            "{symbol}", "Raw R nmath {symbol} ufunc.", 0
        );
        if (ufunc == NULL || PyModule_AddObject(module, "{symbol}", ufunc) < 0) {{
            Py_XDECREF(ufunc);
            Py_DECREF(module);
            return NULL;
        }}
    }}"""
        )

    return f"""/* GENERATED by tools/regen.py -- do not edit. */
#define PY_SSIZE_T_CLEAN
#define NPY_NO_DEPRECATED_API NPY_1_25_API_VERSION
#include <Python.h>
#include <numpy/arrayobject.h>
#include <numpy/ufuncobject.h>
#include <Rmath.h>
#include "accudist_shim.h"

extern void wilcox_free(void);
extern void signrank_free(void);
extern PyThread_type_lock accudist_cache_lock;
extern PyThread_type_lock accudist_rng_lock;

{chr(10).join(loops)}
static PyObject *
py_clear_error(PyObject *self, PyObject *ignored)
{{
    (void)self;
    (void)ignored;
    accudist_clear_error();
    Py_RETURN_NONE;
}}

static PyObject *
py_take_error(PyObject *self, PyObject *ignored)
{{
    (void)self;
    (void)ignored;
    return PyLong_FromUnsignedLong(accudist_take_error());
}}

static PyObject *
py_force_allocation_failure(PyObject *self, PyObject *ignored)
{{
    (void)self;
    (void)ignored;
    accudist_fatal("forced allocation failure: %d", 1);
    Py_RETURN_NONE;
}}

static PyObject *
py_set_seed(PyObject *self, PyObject *args)
{{
    unsigned int i1, i2;
    (void)self;
    if (!PyArg_ParseTuple(args, "II:set_seed", &i1, &i2)) return NULL;
    set_seed(i1, i2);
    Py_RETURN_NONE;
}}

static PyObject *
py_get_seed(PyObject *self, PyObject *ignored)
{{
    unsigned int i1, i2;
    (void)self;
    (void)ignored;
    get_seed(&i1, &i2);
    return Py_BuildValue("(II)", i1, i2);
}}

static PyObject *
py_free_caches(PyObject *self, PyObject *ignored)
{{
    (void)self;
    (void)ignored;
    PyThread_acquire_lock(accudist_cache_lock, WAIT_LOCK);
    wilcox_free();
    signrank_free();
    PyThread_release_lock(accudist_cache_lock);
    Py_RETURN_NONE;
}}

static PyMethodDef module_methods[] = {{
    {{"_clear_error", py_clear_error, METH_NOARGS, NULL}},
    {{"_take_error", py_take_error, METH_NOARGS, NULL}},
    {{"_force_allocation_failure", py_force_allocation_failure, METH_NOARGS, NULL}},
    {{"_set_seed", py_set_seed, METH_VARARGS, NULL}},
    {{"_get_seed", py_get_seed, METH_NOARGS, NULL}},
    {{"_free_caches", py_free_caches, METH_NOARGS, NULL}},
    {{NULL, NULL, 0, NULL}}
}};

static void
module_free(void *module)
{{
    (void)module;
    if (accudist_cache_lock != NULL) {{
        PyThread_acquire_lock(accudist_cache_lock, WAIT_LOCK);
        wilcox_free();
        signrank_free();
        PyThread_release_lock(accudist_cache_lock);
    }}
    accudist_free_locks();
}}

static struct PyModuleDef module_def = {{
    PyModuleDef_HEAD_INIT,
    "_ufuncs",
    "Generated NumPy ufuncs backed by R nmath.",
    -1,
    module_methods,
    NULL,
    NULL,
    NULL,
    module_free
}};

PyMODINIT_FUNC
PyInit__ufuncs(void)
{{
    PyObject *module;
    import_array();
    import_umath();
    if (accudist_init_locks() < 0) {{
        PyErr_NoMemory();
        return NULL;
    }}
    module = PyModule_Create(&module_def);
    if (module == NULL) {{
        accudist_free_locks();
        return NULL;
    }}
{chr(10).join(registrations)}
    return module;
}}
"""


def parameter_list(function: dict, *, typed: bool = False) -> list[str]:
    params: list[str] = []
    special_optional = {"prob", "mu", "scale"}
    for param in function["params"]:
        name = param["py"]
        if function.get("alias") == "rate_scale" and name == "rate":
            default = "None"
        elif name in special_optional:
            default = "None"
        elif "default" in param:
            default = repr(param["default"])
        else:
            default = None
        annotation = ": Any" if typed else ""
        suffix = f" = {default}" if typed and default is not None else (
            f"={default}" if default is not None else ""
        )
        params.append(f"{name}{annotation}{suffix}")
    if function.get("dispatch") == "ncp":
        params.append("ncp: Any = None" if typed else "ncp=None")
    for flag in function["flags"]:
        default = "True" if flag == "lower_tail" else "False"
        params.append(f"{flag}: bool = {default}" if typed else f"{flag}={default}")
    if function["kind"] != "r":
        params.append("out: Any = None" if typed else "out=None")
    return params


def python_call_args(function: dict, call: dict) -> list[str]:
    if function["kind"] in {"d", "p", "q"}:
        args = [function["params"][0]["py"], *call["c_args"]]
    else:
        args = list(call["c_args"])
    args.extend(f"int({flag})" for flag in function["flags"])
    return args


def raw_expression(function: dict, call: dict, *, indent: str) -> str:
    symbol = call["c_symbol"]
    args = python_call_args(function, call)
    if function["kind"] == "r":
        count = function["params"][0]["py"]
        return f"{indent}result = _rng.draw(_ufuncs.{symbol}, {count}, {', '.join(call['c_args'])})"
    return f"{indent}result = _ufuncs.{symbol}({', '.join(args)}, out=out)"


def render_wrapper(function: dict) -> str:
    name = function["name"]
    lines = [
        f"def {name}({', '.join(parameter_list(function))}):",
    ]
    summary = function.get("summary", name + " backed by R 4.5.2 nmath")
    if function["kind"] == "r":
        summary += "; does not reproduce R's set.seed() stream"
    lines.append(f'    """{summary}."""')
    if function.get("alias") == "rate_scale":
        lines.append("    scale = _dispatch.resolve_rate_scale(rate, scale)")
    for target, expression in function.get("c_transform", {}).items():
        if expression == "1.0 / rate":
            lines.append(f"    {target} = _dispatch.reciprocal({target})")
        elif expression == "2.0 if expon_scaled else 1.0":
            lines.append(f"    {target} = 2.0 if {target} else 1.0")
        else:
            raise ValueError(f"unsupported transform for {name}: {expression}")

    if function["kind"] == "r" and function.get("dispatch") == "ncp" and "composed" in function.get("call_ncp", {}):
        central = function["call"]
        lines.append("    if ncp is not None:")
        lines.append("        with _rng.locked():")
        if name == "rbeta":
            lines.extend([
                "            x = rchisq(n, 2 * shape1, ncp=ncp)",
                "            return x / (x + rchisq(n, 2 * shape2))",
            ])
        elif name == "rf":
            lines.append("            return (rchisq(n, df1, ncp=ncp) / df1) / (rchisq(n, df2) / df2)")
        elif name == "rt":
            lines.append("            return rnorm(n, ncp) / _dispatch.sqrt(rchisq(n, df) / df)")
        else:
            raise ValueError(f"unsupported composed RNG {name}")
        lines.append(f"    with _errstate.capture(\"{name}\") as _capture:")
        lines.append(raw_expression(function, central, indent="        "))
    else:
        lines.append(f"    with _errstate.capture(\"{name}\") as _capture:")
        dispatch = function.get("dispatch")
        if dispatch == "ncp":
            lines.append("        if ncp is None:")
            lines.append(raw_expression(function, function["call"], indent="            "))
            lines.append("        else:")
            lines.append(raw_expression(function, function["call_ncp"], indent="            "))
        elif dispatch == "prob_or_mu":
            lines.append("        parameterization = _dispatch.resolve_prob_mu(prob, mu)")
            lines.append("        if parameterization == 'prob':")
            lines.append(raw_expression(function, function["call"], indent="            "))
            lines.append("        else:")
            lines.append(raw_expression(function, function["call_mu"], indent="            "))
        else:
            lines.append(raw_expression(function, function["call"], indent="        "))
    lines.extend(["    _capture.check()", "    return result", ""])
    return "\n".join(lines)


def render_api(functions: list[dict]) -> str:
    pieces = [
        "# GENERATED by tools/regen.py -- do not edit.\n",
        "from __future__ import annotations\n\n",
        "from . import _dispatch, _errstate, _rng, _ufuncs\n\n",
    ]
    pieces.extend(render_wrapper(function) + "\n" for function in functions)
    names = [function["name"] for function in functions]
    pieces.append(f"__all__ = {names!r}\n")
    return "".join(pieces)


def render_stub(functions: list[dict]) -> str:
    lines = [
        "# GENERATED by tools/regen.py -- do not edit.\n",
        "from typing import Any\n",
        "import numpy as np\n\n",
    ]
    for function in functions:
        return_type = "np.ndarray[Any, Any]" if function["kind"] == "r" else "np.float64 | np.ndarray[Any, Any]"
        lines.append(
            f"def {function['name']}({', '.join(parameter_list(function, typed=True))}) -> {return_type}: ...\n"
        )
    return "".join(lines)


def render_rmath(functions: list[dict]) -> str:
    names = list(ufunc_specs(functions))
    lines = [
        "# GENERATED by tools/regen.py -- do not edit.\n",
        '"""Raw, positional, one-to-one mappings to Rmath.h."""\n',
        "from . import _ufuncs\n\n",
    ]
    lines.extend(f"{name} = _ufuncs.{name}\n" for name in names)
    lines.append(f"\n__all__ = {names!r}\n")
    return "".join(lines)


def render_manifest_test(functions: list[dict]) -> str:
    names = [function["name"] for function in functions]
    return f'''# GENERATED by tools/regen.py -- do not edit.
import pytest
import accudist as ad


@pytest.mark.parametrize("name", {names!r})
def test_manifest_function_is_public(name):
    assert callable(getattr(ad, name))
    assert name in ad.__all__
'''


def render_all(manifest: Path) -> dict[str, str]:
    data = tomllib.loads(manifest.read_text())
    functions = enabled_functions(data)
    return {
        "_ufuncs.c": render_c(functions),
        "_api.py": render_api(functions),
        "_generated.pyi": render_stub(functions),
        "rmath.py": render_rmath(functions),
        "test_manifest.py": render_manifest_test(functions),
    }


def write_outputs(outputs: dict[str, str], output_dir: Path, build_mode: bool) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for name, content in outputs.items():
        target = output_dir / name
        if not build_mode and name == "test_manifest.py":
            target = ROOT / "tests" / name
        target.write_text(content)


def check_outputs(outputs: dict[str, str]) -> int:
    failed = False
    for name, content in outputs.items():
        target = GENERATED[name]
        actual = target.read_text() if target.exists() else ""
        if actual == content:
            continue
        failed = True
        print(f"stale generated file: {target.relative_to(ROOT)}")
        print("".join(difflib.unified_diff(actual.splitlines(True), content.splitlines(True))))
    return int(failed)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", nargs="?", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("output_dir", nargs="?", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = render_all(args.manifest)
    if args.check:
        raise SystemExit(check_outputs(outputs))
    output_dir = args.output_dir or ROOT / "accudist"
    write_outputs(outputs, output_dir, build_mode=args.output_dir is not None)


if __name__ == "__main__":
    main()
